### ISSUE TITLE
Issues with pip package (missing attribute detect_language_multi_segment)

### ISSUE THREAD

**Issue by treya-lin** [SYSTRAN/faster-whisper#1008]
Hi, thanks for your great work.

I'd like to report that when I am trying this package, I noticed a weird thing. When I install this package with `pip install`, the code it installed missed some attributes in WhisperModel, so I couldn't run `language_info = model.detect_language_multi_segment(wavpath)
` because `model` has no attribute `detect_language_multi_segment`, it happened both with version 1.0.0 and the upgraded 1.0.3. 

In the github repo I can see that it does have the attribute, but when I entered the package code installed by pip, it does not contain this attribute (and several other attributes are missing too)

Finally I uninstalled the pip installed package, pull the github repo and ran `pip install -e .`, then this time, it is correctly install and I can use the `detect_language_multi_segment` attribute. 

I am not sure if it was because I was using a pip mirror and that mirror was not updated properly (but the version number is correct, so I think it is strange enough). Maybe the author could check if the pip package is updated with all the attributes? And if anyone run into the same issue, just install the package from this repo, it shoule be able to fix it.

**Comment by treya-lin** [comment]
But then I realized after I installed from source, another issue showed up.
when I tried `result = model.transcribe(wavpath, word_timestamps=True, batch_size = 16)`, it told me transcribe has no keyword argument `batch_size` ! (If I install from pip it works properly.)

It is making me confused.

**Comment by Jiltseb** [comment]
Its not an issue with the pip package, rather this change is yet to be released as a Pypi package. The best would be to install from source and use it:
`pip install git+https://github.com/SYSTRAN/faster-whisper.git`

**Comment by MahmoudAshraf97** [comment]
Version `1.1.0` just released to PyPI
