### ISSUE TITLE
Does this project not support Jetson deployment yet

### ISSUE THREAD

**Issue by litao-zhx** [SYSTRAN/faster-whisper#1020]
When I tried to deploy on Jetson, the following error occurred：
![image](https://github.com/user-attachments/assets/771ff125-092c-4726-97ad-c9b69d661b3e)
The deployment code is as follows：
![image](https://github.com/user-attachments/assets/f3ffd79f-6e99-4868-b1ba-3ac59ebb1368)
The Jetson environment is：
![image](https://github.com/user-attachments/assets/19ed366a-aa0a-499b-9f76-8541490516d4)

**Comment by shaielc** [comment]
Encountered the same problem, had to install `CTranslate2` from [source](https://opennmt.net/CTranslate2/installation.html#install-from-sources).

had to turn off MKL and OPENMP (though I didn't try to install openmp) used the following command with cmake:
`cmake .. -DWITH_CUDNN=ON -DWITH_CUDA=ON -DWITH_MKL=OFF -DOPENMP_RUNTIME=NONE`
also you would need to uninstall CTranslate2 if it is already installed.

using the Jetson Nano (8 GB)

**Comment by Joseph513shen** [comment]
> Encountered the same problem, had to install `CTranslate2` from [source](https://opennmt.net/CTranslate2/installation.html#install-from-sources).
> 
> had to turn off MKL and OPENMP (though I didn't try to install openmp) used the following command with cmake: `cmake .. -DWITH_CUDNN=ON -DWITH_CUDA=ON -DWITH_MKL=OFF -DOPENMP_RUNTIME=NONE` also you would need to uninstall CTranslate2 if it is already installed.
> 
> using the Jetson Nano (8 GB)

i met the same problem with jetson nano，Unfortunately, it only supports cuda10, and I don't know if this project supports cuda10.

**Comment by andreclerigo** [comment]
> This problem is better discussed in CTranslate2 Repo

For those looking for it https://github.com/OpenNMT/CTranslate2/issues/1378#issuecomment-1870357659

**Comment by alexismailov2** [comment]
@andreclerigo Yes I have done that before. Thanks for your appreciation!

**Comment by PhilipAmadasun** [comment]
@litao-zhx If you have jetpack 6 you can try my docker image: `uyiosaamadasun/ctranslate2_faster_whisper_v0`. The default gcc compiler on the image is version 10 though, if that matters. I had to do the downgrade to build ctranslate2 successfully.
