### ISSUE TITLE
audio_split example

### ISSUE THREAD

**Issue by Evilmaax** [SYSTRAN/faster-whisper#1021]
Hey guys, right now Im splitting my audio into channels using ffmpeg and numpy, after that I send to `BatchedInferencePipeline.Transcribe` for transcription.

But I was looking at `transcribe.py` class and found a method named `audio_split`. Does it do the same process of separating audio into channels? Cant find any documentation or usage of it. Also, didn't get why segments should be passed as parameter since segments are generated after transcription process.

**Comment by Evilmaax** [comment]
To information of someone who can reach this by having the same question, I went deeper and found that I was misinterpreting the code. 

What this function will really do is receive the audio and the transcribed segments and from its segments start and end time split the audio into corresponding chunks. 

I believe this should be well documented.

**Comment by Jiltseb** [comment]
What `audio_split` does is split the audio into speech segments based on the `start` and `end` times obtained via Voice Activity Detection on the entire audio. 
As you found out, it is not related to splitting the audio into channels. It is a part of the batching process in the `BatchedInferencePipeline `
