### ISSUE TITLE
Turbo-V3

### ISSUE THREAD

**Issue by freddierice** [SYSTRAN/faster-whisper#1025]
I converted the new openai model weights to be used with faster-whisper. Still playing around with it, but in terms of speed its about the same as distil whisper. 

https://huggingface.co/freddierice/openwhisper-turbo-large-v3-ct2/blob/main/README.md

**Comment by nguyenhoanganh2002** [comment]
> I converted the new openai model weights to be used with faster-whisper. Still playing around with it, but in terms of speed its about the same as distil whisper.
> 
> https://huggingface.co/freddierice/openwhisper-turbo-large-v3-ct2/blob/main/README.md

Could you convert Whisper Turbo with the multilingual tokenizer?

**Comment by tjongsma** [comment]
Thanks for the quick conversion! I'm getting a tokenizer error:
```
Traceback (most recent call last):
  File "transcribe.py", line 660, in __init__
    self.hf_tokenizer = tokenizers.Tokenizer.from_file(tokenizer_file)
Exception: data did not match any variant of untagged enum ModelWrapper at line 264861 column 3

```

Any support would be appreciated :)

**Comment by asr-lord** [comment]
> > I converted the new openai model weights to be used with faster-whisper. Still playing around with it, but in terms of speed its about the same as distil whisper.
> > https://huggingface.co/freddierice/openwhisper-turbo-large-v3-ct2/blob/main/README.md
> 
> Could you convert Whisper Turbo with the multilingual tokenizer?

It's done in: https://huggingface.co/deepdml/faster-whisper-large-v3-turbo-ct2

**Comment by Nik-Kras** [comment]
Tested https://huggingface.co/deepdml/faster-whisper-large-v3-turbo-ct2
Works very fast

**Comment by stevevaius2015** [comment]
Could you show how can we test it? On Google Colab notebook I got error as no model named as "faster-whisper-large-v3-turbo-ct2" when `pip install faster-whisper`

**Comment by asr-lord** [comment]
> Could you show how can we test it? On Google Colab notebook I got error as no model named as "faster-whisper-large-v3-turbo-ct2" when `pip install faster-whisper`

You've to download the model in your local:
```python
from huggingface_hub import snapshot_download
repo_id = "deepdml/faster-whisper-large-v3-turbo-ct2"
local_dir = "faster-whisper-large-v3-turbo-ct2"
snapshot_download(repo_id=repo_id,local_dir=local_dir,repo_type="model")
```

**Comment by Nik-Kras** [comment]
If you guys want to test the model as a Real Time Transcription tool - I have a simple demo with Gradio for this. Just updated to code to use "deepdml/faster-whisper-large-v3-turbo-ct2"

https://github.com/Nik-Kras/Live_ASR_Whisper_Gradio

**Comment by stevevaius2015** [comment]
> > Could you show how can we test it? On Google Colab notebook I got error as no model named as "faster-whisper-large-v3-turbo-ct2" when `pip install faster-whisper`
> 
> You've to download the model in your local:
> 
> ```python
> from huggingface_hub import snapshot_download
> 
> repo_id = "deepdml/faster-whisper-large-v3-turbo-ct2"
> local_dir = "faster-whisper-large-v3-turbo-ct2"
> snapshot_download(repo_id=repo_id, local_dir=local_dir, repo_type="model")
> ```

Thanks!

**Comment by asr-lord** [comment]
## Benchmark

For reference, here's the time and memory usage that are required to transcribe [**13 minutes**](https://www.youtube.com/watch?v=0u7tTptBo9I) of audio using different implementations:

* [openai/whisper](https://github.com/openai/whisper)@[6dea21fd](https://github.com/openai/whisper/commit/6dea21fd7f7253bfe450f1e2512a0fe47ee2d258)
* [whisper.cpp](https://github.com/ggerganov/whisper.cpp)@[3b010f9](https://github.com/ggerganov/whisper.cpp/commit/3b010f9bed9a6068609e9faf52383aea792b0362)
* [faster-whisper](https://github.com/guillaumekln/faster-whisper)@[cce6b53e](https://github.com/guillaumekln/faster-whisper/commit/cce6b53e4554f71172dad188c45f10fb100f6e3e)

### Large-v3 model on GPU

| Implementation | Precision | Beam size | Time | Max. GPU memory | Max. CPU memory | WER |
| --- | --- | --- | --- | --- | --- | --- |
| openai/whisper | fp16 | 5 | 4m30s | 11325MB | 9439MB | |
| faster-whisper | fp16 | 5 | 54s | 4755MB | 3244MB | |
| faster-whisper | fp16 | 5 | 54s | 4755MB | 3244MB | |
| faster-whisper | int8 | 5 | 59s | 3091MB | 3117MB | |
| faster-whisper | int8 | 5 | 59s | 3091MB | 3117MB | |

*Executed with CUDA 11.7.1 on a NVIDIA Tesla V100S.*

### Small model on CPU

| Implementation | Precision | Beam size | Time | Max. memory | WER |
| --- | --- | --- | --- | --- | --- |
| openai/whisper | fp32 | 5 | 10m31s | 3101MB | |
| whisper.cpp | fp32 | 5 | 17m42s | 1581MB | |
| whisper.cpp | fp16 | 5 | 12m39s | 873MB | |
| faster-whisper | fp32 | 5 | 2m44s | 1675MB | |
| faster-whisper | int8 | 5 | 2m04s | 995MB | |

*Executed with 8 threads on a Intel(R) Xeon(R) Gold 6226R.*

**Comment by milsun** [comment]
any idea, how can I run it faster using apple silicon, as i have an M2 pro machine.

**Comment by asr-lord** [comment]
> any idea, how can I run it faster using apple silicon, as i have an M2 pro machine.

Have you tried faster-whisper? It'seems that it's faster than any other framework.
https://medium.com/@GenerationAI/streaming-with-whisper-in-mlx-vs-faster-whisper-vs-insanely-fast-whisper-37cebcfc4d27

You could try: https://github.com/mustafaaljadery/lightning-whisper-mlx

**Comment by hockyy** [comment]
lmao the cantonese model is not word to word in the large-v3-turbo one... so sad... :( still will use the large-v3 💖
好嘅 -> 好的 
是否 -> 係咪

**Comment by Nik-Kras** [comment]
> but come on
I don't know that language, could you give more details on your observation? What's wrong and how the result will differ with large-v3?

**Comment by hockyy** [comment]
> > but come on
> 
> I don't know that language, could you give more details on your observation? What's wrong and how the result will differ with large-v3?

`--language=yue`
Used this model
https://huggingface.co/deepdml/faster-whisper-large-v3-turbo-ct2

`--beam_size 10 --best_of 10`

on `https://www.youtube.com/watch?v=sgRfqRFJlAg`

so cantonese has two variants, one is the written cantonese, where all subtitles are mostly based on it, one is the spoken cantonese, which is literally the spoken characters written on it
![image](https://github.com/user-attachments/assets/9e53bf3b-ba2d-4df4-bd7c-712c692ffaa1)
![image](https://github.com/user-attachments/assets/d7380122-a96e-4a1e-8e31-c1987ff11957)

> 藏哥係咪未讀過書?
> 床哥是否未讀過書?

是 => written cantonese variant (read: si)
係 => spoken cantonese variant (read: hai)

In general, if you want to learn spoken cantonese, you'll stick to the spoken version...
The difference is about 10-20%

**Comment by mvoodarla** [comment]
We now support the new whisper-large-v3-turbo on Sieve!

Use it via `sieve/speech_transcriber`: https://www.sievedata.com/functions/sieve/speech_transcriber
Use `sieve/whisper` directly: https://www.sievedata.com/functions/sieve/whisper

Just set `speed_boost` to True. API guide is under "Usage Guide" tab.

**Comment by Jiltseb** [comment]
@trungkienbkhn Will `SYSTRAN` be adding this in the HF repo to be used out of the box?

**Comment by thiswillbeyourgithub** [comment]
> @trungkienbkhn Will `SYSTRAN` be adding this in the HF repo to be used out of the box?

I think that would be necessary for lots of downstream projects like faster-whisper-server

**Comment by asr-lord** [comment]
> > > but come on
> > 
> > 
> > I don't know that language, could you give more details on your observation? What's wrong and how the result will differ with large-v3?
> 
> `--language=yue` Used this model: https://huggingface.co/deepdml/faster-whisper-large-v3-turbo-ct2 vs the normal large-v3 model
> 
> ```
> Faster-Whisper-XXL.exe C:/Users/hocky/Downloads/Video/Video.mp4 --model {MODEL} --device CUDA --output_dir C:/Users/hocky/Downloads/Video --output_format srt --task transcribe --beam_size 10 --best_of 5 --verbose true --vad_filter true --vad_alt_method silero_v4 --standard_asia --language yue
> ```
> 
> on `https://www.youtube.com/watch?v=sgRfqRFJlAg`
> 
> so cantonese has two variants, one is the written cantonese, where all subtitles are mostly based on it, one is the spoken cantonese, which is literally the spoken characters written on it ![image](https://private-user-images.githubusercontent.com/19528709/372501412-9e53bf3b-ba2d-4df4-bd7c-712c692ffaa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTUyNjYsIm5iZiI6MTcyNzg1NDk2NiwicGF0aCI6Ii8xOTUyODcwOS8zNzI1MDE0MTItOWU1M2JmM2ItYmEyZC00ZGY0LWJkN2MtNzEyYzY5MmZmYWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA3NDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YzFhMzg5ZDlmOGFkNDFjMTBlNjYwZGM4YTg3YjU0YzZlOGE4ZWY4OWU4MWY3MzQzMTExNzZiNGJjNmZjODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hiVM89qtLO3ACbRadYzbWPv8z1_SZ8HQ-fcYRKHA4uY) ![image](https://private-user-images.githubusercontent.com/19528709/372501479-d7380122-a96e-4a1e-8e31-c1987ff11957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTUyNjYsIm5iZiI6MTcyNzg1NDk2NiwicGF0aCI6Ii8xOTUyODcwOS8zNzI1MDE0NzktZDczODAxMjItYTk2ZS00YTFlLThlMzEtYzE5ODdmZjExOTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA3NDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNzMyOTdmNmIxYTYyMDkwOTg0MTc2ODc5NzNjOGNjNmNmN2Y4Y2FiNDYyYmMzMmZkNzAyZTFjYWQ0NDM3MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v4z6YPr59OQM5ZCJRfFBLziwyjI-SvQqI3lzaDqHl88)
> 
> > 藏哥係咪未讀過書?
> > 床哥是否未讀過書?
> 
> 是 => written cantonese variant (read: si) 係 => spoken cantonese variant (read: hai)
> 
> In general, if you want to learn spoken cantonese, you'll stick to the spoken version... The difference is about 10-20%
> 
> bruh, just realized it doesn't even transcribe the most basic terms properly: the famous "DLLM"

You may find this discussion helpful:
https://github.com/openai/whisper/discussions/2363#discussion-7264254
"Across languages, the turbo model performs similarly to large-v2, though **it shows larger degradation on some languages like Thai and Cantonese.**"
![image](https://github.com/user-attachments/assets/8deee44b-e611-4148-adce-eb45fb28f217)

**Comment by tjongsma** [comment]
> If you guys want to test the model as a Real Time Transcription tool - I have a simple demo with Gradio for this. Just updated to code to use "deepdml/faster-whisper-large-v3-turbo-ct2"
> 
> https://github.com/Nik-Kras/Live_ASR_Whisper_Gradio

What's your experience with using v3-turbo for short audio clips? Mine has been that unfortunately it performs worse than other models, see https://github.com/SYSTRAN/faster-whisper/issues/1030#issuecomment-2393164779

**Comment by Nik-Kras** [comment]
> What's your experience with using v3-turbo for short audio clips? Mine has been that unfortunately it performs worse than other models, see [#1030 (comment)](https://github.com/SYSTRAN/faster-whisper/issues/1030#issuecomment-2393164779)

I only planned to evaluate turbo, turbo-CTranslate2 and turbo-HQQ. I can only tell that it works x2-x3 times faster based on my logs with the Gradio demo.

How bad are the evaluation results?

**Comment by asr-lord** [comment]
> > What's your experience with using v3-turbo for short audio clips? Mine has been that unfortunately it performs worse than other models, see [#1030 (comment)](https://github.com/SYSTRAN/faster-whisper/issues/1030#issuecomment-2393164779)
> 
> I only planned to evaluate turbo, turbo-CTranslate2 and turbo-HQQ. I can only tell that it works x2-x3 times faster based on my logs with the Gradio demo.
> 

How do you use HQQ in faster-whisper? Could you share a sample code? 
I only see how to use it with Transformers library: https://github.com/mobiusml/hqq?tab=readme-ov-file#transformers-

**Comment by Nik-Kras** [comment]
> > > What's your experience with using v3-turbo for short audio clips? Mine has been that unfortunately it performs worse than other models, see [#1030 (comment)](https://github.com/SYSTRAN/faster-whisper/issues/1030#issuecomment-2393164779)
> > 
> > 
> > I only planned to evaluate turbo, turbo-CTranslate2 and turbo-HQQ. I can only tell that it works x2-x3 times faster based on my logs with the Gradio demo.
> 
> How do you use HQQ in faster-whisper? Could you share a sample code? I only see how to use it with Transformers library: https://github.com/mobiusml/hqq?tab=readme-ov-file#transformers-

Right, HQQ works with Transformers. But faster-whisper is just whisper accelerated with CTranslate2 and there are models of turbo accelerated with CT2 available on HuggingFace: deepdml/faster-whisper-large-v3-turbo-ct2

Also, HQQ is integrated in Transformers, so quantization should be as easy as passing an argument 
```python
model_id = "deepdml/faster-whisper-large-v3-turbo-ct2"
quant_config = HqqConfig(nbits=4, group_size=64)

model = AutoModelForSpeechSeq2Seq.from_pretrained(
    model_id,
    torch_dtype=torch_dtype,
    low_cpu_mem_usage=True,
    use_safetensors=True,
    quantization_config=quant_config
)
```
https://huggingface.co/docs/transformers/main/quantization/hqq

I didn't try it yet, so don't know if that is going to work.
How about to have a chat about it outside of the GitHub issue? Send me a message on LinkedIn, I have it attached in the profile

**Comment by Jiltseb** [comment]
No, There is no HQQ support for ctranslate2 yet.

Faster-whisper has whisper models in `Ctranslate2` format, which is different from `pytorch` models in HF. Of course the models are available in HF so that it is easy to use in packages such as faster-whisper. But one can not directly load a ctranslate2 checkpoint with  `AutoModelForSpeechSeq2Seq`.

I have created a feature request in the past to support HQQ (with static cache and torch compilation): https://github.com/OpenNMT/CTranslate2/issues/1717

The [PR](https://github.com/OpenNMT/CTranslate2/pull/1738) is still in progress and it has some performance issues that needs to be fixed.

**Comment by tjongsma** [comment]
> > What's your experience with using v3-turbo for short audio clips? Mine has been that unfortunately it performs worse than other models, see [#1030 (comment)](https://github.com/SYSTRAN/faster-whisper/issues/1030#issuecomment-2393164779)
> 
> I only planned to evaluate turbo, turbo-CTranslate2 and turbo-HQQ. I can only tell that it works x2-x3 times faster based on my logs with the Gradio demo.
> 
> How bad are the evaluation results?

No standardized evaluation or anything, I'm just running it in my streaming application and seeing way worse results than medium (especially with it randomly just not transcribing part of the text). This is a ctranslate2 implementation, deepdml/faster-whisper-large-v3-turbo-ct2 to be exact. See my linked comment for the code

**Comment by silvacarl2** [comment]
were you able to convert turbo to faster-whisper format?

**Comment by Jiltseb** [comment]
[Mobiuslabs fork]( https://github.com/mobiusml/faster-whisper) now supports `turbo` out of the box, and has additional fixes.

**Comment by freddierice** [comment]
There seems to be a lot of confusion in this thread -- if you want to use turbo with the current faster whisper, all you have to do is 
```
WhisperModel("deepdml/faster-whisper-large-v3-turbo-ct2", device="cuda", compute_type="float16")
```

Closing this thread since there is no issue.

**Comment by NingLu** [comment]
> deepdml/faster-whisper-large-v3-turbo-ct2

This is exactly what I need, thank you
