### ISSUE TITLE
BatchedInferencePipeline missing in PyPi release

### ISSUE THREAD

**Issue by CrispStrobe** [SYSTRAN/faster-whisper#1031]
the transcribe.py that gets installed by pip install differs largely from the one in the current repo. especially, BatchedInferencePipeline is not present there. so one has to git clone & pip install -r requirements.txt to get a working batch pipeline etc. maybe there was an issue in release preparation?

**Comment by MahmoudAshraf97** [comment]
it wasn't released yet, install from source if you want to use it

**Comment by Pedrexus** [comment]
Thank you for the info. Do we have an ETA for next release?

**Comment by MahmoudAshraf97** [comment]
I don't know unfortunately

**Comment by MahmoudAshraf97** [comment]
Version `1.1.0` just released to PyPI
