### ISSUE TITLE
ETA of 1.0.4? Batched inference for pip package

### ISSUE THREAD

**Issue by phu54321** [SYSTRAN/faster-whisper#1062]
Hello, I'm using [batched inference mode](https://github.com/SYSTRAN/faster-whisper?tab=readme-ov-file#batched-faster-whisper) very well. I'm now opting in for master branch of this repo for installation. I wonder when will this feature will be pushed to PyPI. Is there any ETA?

Thanks.

**Comment by MahmoudAshraf97** [comment]
Version `1.1.0` just released to PyPI
