### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by YasinSharifbeigy** [SYSTRAN/faster-whisper#1074]
I downgraded to version 1.0.0 and noticed a significant decrease in performance (20x slower !!). The output quality has also worsened, with the text repeated multiple times. Is it possible to fix it?

**Comment by MahmoudAshraf97** [comment]
Unless there's a solid reason to downgrade, don't do it

**Comment by MahmoudAshraf97** [comment]
Use this instead
https://github.com/MahmoudAshraf97/whisper-diarization/tree/batched_fw

**Comment by Nyralei** [comment]
Try my fork of whisperX with updated faster-whisper and other stuff
https://github.com/Nyralei/whisperX
