### ISSUE TITLE
C++ version for faster_whisper

### ISSUE THREAD

**Issue by BaffledCoder** [SYSTRAN/faster-whisper#1075]
Is there a C++ version of SYSTRAN/faster-whisper

This request is specifically for creating a C++ version that replicates the functionality of the Python implementation, with the following key features:

High-speed transcription capabilities.
Compatibility with existing models and weights from the Python version.
Cross-platform support (Linux, Windows, macOS).
Minimal dependencies for easy integration into existing C++ projects.

**Comment by MahmoudAshraf97** [comment]
Faster whisper is already a python wrapper around a c++ runtime which is ctranslate2، you can use that directly and there are discussions about that in CT2 repo

**Comment by BaffledCoder** [comment]
Thanks a lot. I will check that
