### ISSUE TITLE
VOTE HERE - transfer of maintaining faster-whisper repo

### ISSUE THREAD

**Issue by BBC-Esq** [SYSTRAN/faster-whisper#1078]
For all who like faster-whisper, go to this issue on ctranslate2's main page and give your feed back.  It doesn't have to agree with mine, but give your opinion nonetheless so the recalcitrant peeps at "Systran" (whatever the heck they do, who knows) can make a decision ASAP.  Thanks!

https://github.com/OpenNMT/CTranslate2/issues/1802

**Comment by nguyendc-systran** [comment]
Please check the answer here: https://github.com/OpenNMT/CTranslate2/issues/1802#issuecomment-2431773316
