### ISSUE TITLE
KernelRestarter: restarting kernel (1/5), keep random ports

### ISSUE THREAD

**Issue by etb-git1** [SYSTRAN/faster-whisper#1081]
from faster_whisper import WhisperModel

model_size = "large-v3"

--- Run on GPU with FP16 precision

model = WhisperModel(model_size, device="cuda", compute_type="float16")

-- Transcribe the audio file
model.transcribe("/content/newa.mp3")
Issue: When this command is executed, Google Colab restarts the kernel. The logs show the following:

html
Copiar código
Timestamp               | Level    | Message
------------------------|----------|-------------------------------------------------
Oct 23, 2024, 11:39:33 AM | WARNING | WARNING:root: kernel 809d6880-5cdc-4a67-b46f-e92269ffec4a restarted
Oct 23, 2024, 11:39:33 AM | INFO    | KernelRestarter: restarting kernel (1/5), keep random ports
Oct 23, 2024, 11:39:31 AM | WARNING | Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor
Oct 23, 2024, 11:39:31 AM | WARNING | Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}

This issue started occurring yesterday.

gpu is:

NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

**Comment by bernardocecchetto** [comment]
I am facing the same problem in databricks. Any solution?

**Comment by kristopher-smith** [comment]
Same issue here. As a workaround, install ctranslate2==4.4.0 or previous version from here:  https://pypi.org/project/ctranslate2/#history

faster-whisper automatically installs the latest version of ctranslate2 between 4.0-5.0. Just so happens that yesterdays ctranslate2 release breaks faster-whisper.

Hope this helps!

**Comment by etb-git1** [comment]
hi Mate , your solution works out!

—thank you so much!

 I'm currently using pip install ctranslate2==4.4.0, and everything is running smoothly."

**Comment by etb-git1** [comment]
fixed it!!

**Comment by EtienneAb3d** [comment]
You need to install latest cuda toolkit, then cuDNN 9:
https://docs.nvidia.com/deeplearning/cudnn/latest/installation/linux.html

Typical example with cuda 12 installed on Ubuntu:
![image](https://github.com/user-attachments/assets/72fdc72f-3d9e-40bf-acb8-c6ce5d6d94b9)

```
#Cuda toolkit 12
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/12.6.2/local_installers/cuda-repo-ubuntu2004-12-6-local_12.6.2-560.35.03-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu2004-12-6-local_12.6.2-560.35.03-1_amd64.deb
sudo cp /var/cuda-repo-ubuntu2004-12-6-local/cuda-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install cuda-toolkit-12-6

#CUDNN 9 for cuda 12
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
sudo apt-get update
sudo apt-get -y install cudnn9-cuda-12
```

**Comment by EtienneAb3d** [comment]
Additional information! 

When using 2 models using cuDNN 9 in the same software, for example Demucs + Fast-Whisper, I get this error for the second one:

`Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}`

When using only one of them, with the above cuDNN 9 for Cuda 12 installation, all is ok.
