### ISSUE TITLE
Latest CTranslate2 release breaks faster-whisper

### ISSUE THREAD

**Issue by kristopher-smith** [SYSTRAN/faster-whisper#1083]
The latest release of CTranslate2 python library from 10-22-2024 breaks faster-whisper. See release history here: https://pypi.org/project/ctranslate2/4.4.0/#history

I have created a pull request to fix this issue with a simple update to the requirements.txt file: https://github.com/SYSTRAN/faster-whisper/pull/1082

Hope this helps!

**Comment by MahmoudAshraf97** [comment]
what version of torch are you using?

**Comment by MahmoudAshraf97** [comment]
#1086
