### ISSUE TITLE
Loop task, transcribe after obtaining new audio files. Eventually, it will boom

### ISSUE THREAD

**Issue by Gitawake** [SYSTRAN/faster-whisper#1098]
```
model_size = "./model_tiny"
model = WhisperModel(model_size, device="cpu", compute_type="int8")

def audio_identify():
    while True:
        audio_file = audio_state.get_and_remove_audio_segment()
        if audio_file is not None:
            audio_state.set_transcribe_state("1")
            start_identify_time = time.time()
            logger.info(f"Processing file: {audio_file}")
            segments, info = model.transcribe(audio_file, beam_size=5, vad_filter=True)
            for segment in segments:
                dict_text = {audio_state.increment_list_index(): segment.text}
                logger.info(dict_text)
                audio_state.set_add_text_list(dict_text)

            end_identify_time = time.time()

            logger.info(f"Identification duration: {end_identify_time - start_identify_time:.2f} 秒")

        else:
            if audio_state.get_audio_state() != "1":
                audio_state.set_transcribe_state("0")
                logger.warning("Identification completed")
            time.sleep(2)
```
May I ask if anyone can help me solve my programming problem? I don't know if there is a problem with my code. How should I loop because I am recording audio once and saving the file for transcription every 6 seconds.

A few minutes or more of task execution can cause the device to crash

The same code only needs to be replaced with other Whisper libraries to avoid crashing, but it cannot meet my needs in terms of efficiency and functionality

**Comment by MahmoudAshraf97** [comment]
post the error traceback so people can help, also add more details such as system specs, and environment

**Comment by Gitawake** [comment]
> post the error traceback so people can help, also add more details such as system specs, and environment

I'm sorry! There are no errors. I am running Ubuntu 18.4 on rk3568B2 with 4GB of memory, but the system is experiencing screen freezing. Can only force restart
