### ISSUE TITLE
Custom VAD config with BatchedInferencePipeline

### ISSUE THREAD

**Issue by vidalfer** [SYSTRAN/faster-whisper#1109]
How can I customize the VAD parameters used by the BatchedInferencePipeline? The following code, based on the repository's reference code, doesn't work, as it says there's no vad_filter parameter.
```python
model = WhisperModel(model_name, device=device, compute_type="float16" if device == "cuda" else "int8")
batched_model = BatchedInferencePipeline(model=model)
results, _ =  batched_model.transcribe(audio_file, language='pt', **asr_options,batch_size=64,vad_filter=True)
```

**Comment by MahmoudAshraf97** [comment]
you should pass them to the `vad_parameters` argument in `batched_model.transcribe`
