### ISSUE TITLE
Is this compatible with tinydiarize?

### ISSUE THREAD

**Issue by mathigatti** [SYSTRAN/faster-whisper#1116]
I wonder if I can use this whisper optimization with [this fine tuned version of whisper](https://github.com/akashmjn/tinydiarize) that transcribes speech + speaker turns.

It has compatibility with whisper.cpp [[ref]](https://huggingface.co/akashmjn/tinydiarize-whisper.cpp)

**Comment by MahmoudAshraf97** [comment]
It's compatible with a few (maybe?) extra steps, you'll need to convert the checkpoint to CT2 format and the tokenizer might also need modification
