### ISSUE TITLE
 fasterwhisper  and cuda version 

### ISSUE THREAD

**Issue by zhuangzhuangliu2345** [SYSTRAN/faster-whisper#1120]
I used ctranslate2 in fasterwhisper, and I am using the latest version of ctranslate2. However, I received an error stating that the CUDA version is incorrect. After dropping it to 3.2.40, I was informed that the CUDA. so file is missing.
Do you guys use CUDA 11.8 or not? What are the versions of Fasterwhisper and CTranslate2. tanks 
![b0e54d1f77cd5801237ec7817354cb5](https://github.com/user-attachments/assets/bf0c14d3-d363-48ed-8892-20e91af52317)

![451a8c48d714b6b239e7e1b95aafd3f](https://github.com/user-attachments/assets/79d0c8bd-64a1-469c-9969-3e62b1d3edad)

**Comment by MahmoudAshraf97** [comment]
What versions of cuda packages are you using along with CT2 4.*?

**Comment by zhuangzhuangliu2345** [comment]
ct:3.24.0

**Comment by zhuangzhuangliu2345** [comment]
av 10.0.0   faster-whisper 0.10.1

**Comment by Genesis1231** [comment]
the best bet is go to 12+ and cudnn9 for the latest ctran

**Comment by davidecantoni** [comment]
Please do have a look at the metrix here https://github.com/SYSTRAN/faster-whisper/issues/1086

**Comment by zhuangzhuangliu2345** [comment]
The question is, my current machine supports CUDA11.8/11.4. Is there a recommended CT version? Am I unable to use FasterWhisper with  CUDA11.8/4 version。thanks lot for you help

**Comment by zhuangzhuangliu2345** [comment]
The question is, my current machine supports CUDA11.8/11.4. Is there a recommended CT version? Am I unable to use FasterWhisper with CUDA11.8/4 version。 thanks a lot for your help

**Comment by zhuangzhuangliu2345** [comment]
11.4 can use with ct 3.2.0 and faster-whisper 0.10.1
