### ISSUE TITLE
Possible way to integrate support for Intel Iris Xe gpus?

### ISSUE THREAD

**Issue by gimmeAll** [SYSTRAN/faster-whisper#1121]
I have a lot of school lectures that I need to make notes of, and using this plugin to transcribe the words would make doing so much easier. However, I only have access to my Intel laptop for computation, and I assume that if I could use the onboard Iris Xe GPU, the transcription rate would increase significantly. I did find the following resource for packages to install to enable support. Still, I don't know how to reformulate the options on transcribe.py to enable it to work (I assume, though it is windows specific, that it could work on my Linux machine): https://stackoverflow.com/questions/76796848/how-to-enable-intel-iris-xe-gpu-for-tensorflowkeras-on-windows

**Comment by MahmoudAshraf97** [comment]
The correct place to open this issue is in https://github.com/OpenNMT/CTranslate2
