### ISSUE TITLE
Hidden state / embeddings of encoder

### ISSUE THREAD

**Issue by SinanAkkoyun** [SYSTRAN/faster-whisper#1132]
Hi! Is it possible to retrieve the encoders embeddings?

**Comment by MahmoudAshraf97** [comment]
It's, use `model.encode` function which takes in features with shape `(batch_size, n_mels, seq_length)`

**Comment by SinanAkkoyun** [comment]
Hi, I made a PR enabling the retrieval of embeddings whilst still retaining old usage
https://github.com/SYSTRAN/faster-whisper/pull/1136

**Comment by SinanAkkoyun** [comment]
@MahmoudAshraf97 
Hi, I made a PR enabling the retrieval of embeddings whilst still retaining old usage
https://github.com/SYSTRAN/faster-whisper/pull/1136
