### ISSUE TITLE
Batch size impact on speed and VRAM consumption

### ISSUE THREAD

**Issue by vidalfer** [SYSTRAN/faster-whisper#1143]
I ran some tests with different batch sizes and noticed that neither VRAM usage nor transcription speed changed significantly. I tested with batch sizes of 64, 128, and 512 on an A100 GPU. Is this normal? Theoretically, VRAM usage should increase along with speed as the batch size grows. I'm using the batched pipeline in my tests.

**Comment by pablopla** [comment]
How does batching work on CPU? Without batching I don't see improvement in transcription speed above 4 threads. Does batching allows me to use more threads? Is batching supposed to also improve transcription speed on 4 threads compare to no batching?

**Comment by MahmoudAshraf97** [comment]
I don't use it on CPUs unfortunately, feel free to test it and report the results
