### ISSUE TITLE
No need to install cuda driver?

### ISSUE THREAD

**Issue by ILG2021** [SYSTRAN/faster-whisper#1147]
I see faster whisper is depend on cudnn and cublas, should I need to install cuda:
https://developer.download.nvidia.com/compute/cuda/12.1.0/local_installers/cuda_12.1.0_531.14_windows.exe

**Comment by joseph16388** [comment]
> I see faster whisper is depend on cudnn and cublas, should I need to install cuda: https://developer.download.nvidia.com/compute/cuda/12.1.0/local_installers/cuda_12.1.0_531.14_windows.exe

yes
