### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by RuntimeRacer** [SYSTRAN/faster-whisper#1155]
There have been 23 commits to master since the last official release for this repo: https://github.com/SYSTRAN/faster-whisper/compare/v1.0.3...master

In one of my projects which uses faster-whisper with BatchedInferencePipeline I have to do implement hacky setup solutions because of this.
Would be great if you guys could release a new tag from time to time. :-)

**Comment by MahmoudAshraf97** [comment]
It'll be released soon, there are just some sharp edges that need to be dealt with first
