### ISSUE TITLE
New model: CrisperWhisper

### ISSUE THREAD

**Issue by imsakg** [SYSTRAN/faster-whisper#1162]
I would like to bring attention to the recent release of the new Whisper model, which has demonstrated significant performance on the [OpenASR leaderboard](https://huggingface.co/spaces/hf-audio/open_asr_leaderboard). This advancement in ASR technology is noteworthy and could have implications for faster-whisper.

References:
	- [CrisperWhisper](https://huggingface.co/nyrahealth/CrisperWhisper)
	- [OpenASR Leaderboard](https://huggingface.co/spaces/hf-audio/open_asr_leaderboard)

**Comment by Purfview** [comment]
Issues is not a proper place to post such.

Make a post in Discussions: https://github.com/SYSTRAN/faster-whisper/discussions/categories/show-and-tell
