### ISSUE TITLE
sound-effects missing on output for beam-size > 1

### ISSUE THREAD

**Issue by rummyr** [SYSTRAN/faster-whisper#1170]
If I transcribe with a beam_size of 1 I seem to get tokens like..
[0.00s -> 5.08s]  MUSIC
[16.08s -> 17.84s]  speech as text,
[17.84s -> 20.24s]  speech as text
[20.24s -> 22.96s]  speech as text
[22.96s -> 25.76s]  CHEERING AND APPLAUSE
[25.76s -> 28.80s]  speech as text

but with beam_sizes > 1 I just get the speech and no 'sound-effects'
ideally I would like the [MUSIC] [LAUGHTER] etc.

Can this be done?

**Comment by Purfview** [comment]
>'sound-effects'... Can this be done?

Not with whisper models, it does only speech to text.

>sound-effects missing on output for beam-size > 1

You mean hallucinations are missing.

**Comment by rummyr** [comment]
hallucinations .. 
  fair enough, it's a speech transcriber, so it isn't unreasonable if it doesn't want to output e.g. BUZZER.
  though since it will do so in some circumstances I thought perhaps it was something that could be tweaked.

**Comment by Purfview** [comment]
> since it will do so in some circumstances I thought perhaps it was something that could be tweaked.

It can, use VAD to reduce hallucinations.
