### ISSUE TITLE
OOM when using VAD

### ISSUE THREAD

**Issue by Troffifi** [SYSTRAN/faster-whisper#1193]
Hi, does somebody else experience issues with memory consumption when transcribing audio files containing a lot of speech (~ 4 hours long)? I am running the latest version of faster-whisper in a Kubernetes pod on a g4dn AWS instance. The server has 4 cores, 1 GPU, and 16GB RAM, but the pod is limited to 2 cores. The base image is `pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime` and as per [this pinned issue](https://github.com/SYSTRAN/faster-whisper/issues/1086) the installed versions should be compatible:
- python 3.11
- torch 2.5.1+cu124
- ctranslate2 4.5.0
- cuda 12.4
- cudnn 9.1.0.7

The process gets killed during the transcription phase when VAD is enabled. I tried the solution [described here](https://github.com/snakers4/silero-vad/issues/356), but it doesn't help. See the logs attached. Anyone has any idea what could be the cause of the OOM?

[libraries.txt](https://github.com/user-attachments/files/18039471/libraries.txt)
[logs on sigkill.txt](https://github.com/user-attachments/files/18039459/logs.on.sigkill.txt)

**Comment by Purfview** [comment]
Try this fix -> https://github.com/SYSTRAN/faster-whisper/pull/1198

**Comment by Troffifi** [comment]
I still have to run some tests, but I tried it and it looks promising. The[ latest commit](https://github.com/SYSTRAN/faster-whisper/pull/1198/commits/4c456f59aacf93a0ae29aa4918601de55953f2be) has fixed it. Thank you @Purfview! I will let you know if the issue persists.
