### ISSUE TITLE
API call 

### ISSUE THREAD

**Issue by denisjoshua** [SYSTRAN/faster-whisper#1197]
Hi there all, 
I'm not sure if it's a stupid question but I try :-) 

Is there possibility to make an API call to the faster-whisper please ? 
I have installed in a docker in my LAN and it's work for calls from Home Assistant. 
But if I want to make a call from some HTTP Request is not work... or maybe I don't know how to make it. 

Also I want to make a call from n8n workflow is someone can help me. 
Thanks a lot in advance. 
Denis

**Comment by denisjoshua** [comment]
Normally the Home Assistant users install the Whisper like add-on in HAS
But if you want to have more power from Whisper (maybe also use of GPU) then you can install a Whisper server on you LAN.

If I understand also Home Assistant add-on use this version of Whisper (the Faster-Whisper) 
So I installed a Docker in my LAN that use Faster-Whisper with GPU ... and is more power, and more quick. 

What I don't know yes is how can I call Faster-Whisper like an OpenAI API call.
How can I make a HTTP Request from my n8n workflow. 

Thanks again 
Denis

**Comment by heimoshuiyu** [comment]
There are many projects that provide OpenAI API for Faster-Whisper, such as 

- https://github.com/heimoshuiyu/whisper-fastapi
- https://github.com/fedirz/faster-whisper-server

, or you can write your own script. It is simple if you known python

For wyoming protocol with Home Assistant,  I found https://github.com/rhasspy/wyoming-faster-whisper

**Comment by denisjoshua** [comment]
I have already install the [faster-whisper-server](https://github.com/fedirz/faster-whisper-server) but is not more work for my Home Assistant calls. Also I don't know why didn't fins my GPU driver. 
I think, but not sure, that that version have not the  wyoming protocol.

I need a version that work in same time with Home Assistant calls 
and also with API calls via HTTP Request. 
Do you know please witch one can make this

**Comment by heimoshuiyu** [comment]
Unfortunately, I don't know where such a project exists. 

However, the Wyoming protocol is relatively simple, so I implemented it myself. <https://github.com/heimoshuiyu/whisper-fastapi/blob/master/whisper_fastapi.py#L440>

Since faster-whisper itself has no plans to provide a network API, I believe this issue is unrelated to this repository. We might consider closing this issue.

**Comment by denisjoshua** [comment]
Thanks a lot for implementing... 
I'll try your version in order to have API call and Wyoming protocol on same docker. 
I have found also [faster-whisper-server](https://github.com/fedirz/faster-whisper-server) that implemented API call, 
but this one also have not a Wyoming protocol I think :-(  
Thanks again 
Denis
