### ISSUE TITLE
a little confused about the benchmark results

### ISSUE THREAD

**Issue by ywangwxd** [SYSTRAN/faster-whisper#1201]
Maybe I have not understood the latency metric correctly. I noticed that if we use faster-whisper, the latency of non-batch vs batch_size=8 is 1.03ms vs 17ms, the latter is almost 16 times of the former, but we only have batch size 8, so what is the benefit?

**Comment by MahmoudAshraf97** [comment]
this is the time taken to transcribe the mentioned file, one is 1 minute 3 seconds which is 63 seconds vs 17 seconds, that's almost 4 times faster

**Comment by ywangwxd** [comment]
> this is the time taken to transcribe the mentioned file, one is 1 minute 3 seconds which is 63 seconds vs 17 seconds, that's almost 4 times faster

Sorry, I misread the time, 1m03 is 1 minute 3 second.
