### ISSUE TITLE
Bug: Faster-Whisper fails on no-speech audio due to language detection error

### ISSUE THREAD

**Issue by le-luchina** [SYSTRAN/faster-whisper#1208]
**Description**
The `transcribe` method fails with a `ValueError` (`max() arg is an empty sequence`) when processing audio files with no speech, especially after VAD filtering. This issue occurs during language detection when no segments remain after filtering.

**Steps to Reproduce**
1. Use an audio file with no discernible speech or where VAD filters remove all speech.
2. Call `transcribe` with `vad_filter=True`.
3. Observe the following error:
   ```plaintext
   ValueError: max() arg is an empty sequence

**Expected Behavior**
The method should return a transcription object with empty or None fields instead of raising an error.

**Environment**
Faster-Whisper Version: 1.0.3
Python Version: 3.10
OS: Ubuntu 22.04
GPU

**Suggested Fix**
Add a check after VAD filtering to handle empty audio gracefully and return a formatted but empty result.

**Error Traceback**

File "/opt/src/audio/transcript_extractor.py", line 280, in _transcribe
  transcription_segments, transcription_info = model.transcribe(
File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 419, in transcribe
  language = max(…
ValueError: max() arg is an empty sequence

**Comment by MahmoudAshraf97** [comment]
This was solved in the latest version, please update and test again
