### ISSUE TITLE
System Crash when running on colab

### ISSUE THREAD

**Issue by kishlaykumar1995** [SYSTRAN/faster-whisper#1216]
I am trying to run a faster whisper (large-v3) model on colab (T4 GPU) and it crashes with unknown reasons.
Here is my code:
```
!pip install faster-whisper
!pip install peft

from faster_whisper import WhisperModel
model_size = "large-v3"
model = WhisperModel(model_size, device="cuda", compute_type="int8_float16")

segments,_ = model.transcribe('/content/test.mp3', language='en')
segments = list(segments)
```

Tried the same on kaggle and another vm but same issue. Can't see any error/logs but the kernel crashes and restarts everytime. Any idea what the issue is?

**Comment by DariaMishina** [comment]
I have the same issue

**Comment by md0121** [comment]
I've had the same issue. I think it is CPU spike causing the crash. I've tried your commands and it is working for me now strangely. Not sure if it is the cuda versions or whether I did something different.

**Comment by FYC23** [comment]
I had the same issue on my end, and for me it was Colab's cuDNN version (8.9.6 instead of 9). 
It worked after I reinstalled a diff version of ctranslate (4.4.0) according to faster whisper's readme.

**Comment by md0121** [comment]
Thanks that seems to have solved it.

**Comment by kishlaykumar1995** [comment]
> I had the same issue on my end, and for me it was Colab's cuDNN version (8.9.6 instead of 9). 
> 
> It worked after I reinstalled a diff version of ctranslate (4.4.0) according to faster whisper's readme. 

Thanks. This seems to fix the issue. I will close the issue.
