### ISSUE TITLE
Is there a way to overcome the Segmentation fault: 11 error on a mac?

### ISSUE THREAD

**Issue by madalinstan-greppysystems** [SYSTRAN/faster-whisper#137]

**Comment by guillaumekln** [comment]
Can you give more details?

**Comment by madalinstan-greppysystems** [comment]
Yes, so basically I run the faster-whisper model on an audio file on my mac, which has got a Monterey 12.1 OS and it gives the error that I've mentioned. I was thinking that I might not be the only one who uses a mac to run faster-whisper, and I couldn't find a working solution anywhere. As I noticed this a typical mac error in Python, but as I said I was hoping that someone else might have encountered this.

**Comment by guillaumekln** [comment]
There was another report of a segmentation fault on Mac but it was during the model conversion #18. The issue was resolved by creating a new Python virtual environment.

If that does not solve your issue, you should describe how to reproduce the issue (model size, audio file, transcription options, etc.).

**Comment by madalinstan-greppysystems** [comment]
Okay, I'm gonna create a new virtual environment and see whether that will help.

**Comment by mkandan** [comment]
> Okay, I'm gonna create a new virtual environment and see whether that will help.

Did it help? @madalinstan-greppysystems

**Comment by madalinstan-greppysystems** [comment]
No, it did not, same thing happens.

**Comment by stasbel** [comment]
I still have segfaults on mac
apparently, this have something to do with numpy
also, I got this error message for simple script with faster-whisper model
```
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
[1]    26161 abort      python error.py
```
having KMP_DUPLICATE_LIB_OK=TRUE also ends up with segfault

**Comment by guillaumekln** [comment]
Does it work fine when PyTorch is not imported?

**Comment by stasbel** [comment]
yes

**Comment by shahzebali42** [comment]
getting the same error and python crashes

**Comment by ethanzrd** [comment]
> I still have segfaults on mac apparently, this have something to do with torch: when it does imported, faster-whisper ends up in segfaulting
> 
> I got this error message for simple script with faster-whisper model
> 
> ```
> OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
> OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
> [1]    26161 abort      python error.py
> ```
> 
> having KMP_DUPLICATE_LIB_OK=TRUE also ends up with segfault

This is also happening to me.

```
INFO:faster_whisper:Processing audio with duration 00:09.500

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

This starts happening right after I install Diart: `pip install diart`

**Comment by robinderat** [comment]
I think I have traced the source of the problem back to ctranslate2.

In my case I got a SIGSEGV when trying to run both faster-whisper and wav2vec. As in the following minimal reproduction case
```
from faster_whisper import WhisperModel
from transformers import Wav2Vec2ForCTC

m = Wav2Vec2ForCTC.from_pretrained("jonatasgrosman/wav2vec2-large-xlsr-53-dutch")
```
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

The same happens when replacing `from faster_whisper import WhisperModel` with `import ctranslate2`

Looking at the ctranslate2/__init__.py, there are imports from a compiled extension

```
try:
    from ctranslate2._ext import (
      [...]
)
except ImportError as e:
    # Allow using the Python package without the compiled extension.
    if "No module named" in str(e):
        pass
    else:
        raise
```

After removing this import block, the wav2vec model can load without the SIGSEGV.

Unfortunately, faster-whisper relies on these imports, like `StorageView` and ctranslate2.models, making it no longer possible to initialize WhisperModel after this edit.

My setup is:
MacOs 13.5 Intel
python 3.10
faster-whisper==0.7.1
transformers==4.31.0

The above example has been verified to run without SIGSEGV on MacOs ARM + python3.10 and MacOs Intel + python3.8, leading me to believe the problem lies in ctranslate2 packaged `_ext.cpython-310-darwin.so` (based on my os and python version)

**Comment by tomriddly** [comment]
Maybe you can try my solution here: [#541](https://github.com/guillaumekln/faster-whisper/issues/541#issuecomment-1805255813)

**Comment by avi-cenna** [comment]
For anyone else who got the SIGSEGV (aka segmentation fault) error on MacOS. I did the following and it worked on my machine:

1. Create a new poetry project: `poetry new [project name] && cd [project name]`
2. Set python 3.10 as local version: `pyenv local 3.10`
3. Set poetry env to use 3.10: `poetry env use 3.10`
4. Add faster whisper and loguru: `poetry add faster-whisper loguru`
5. Create a minimal example, which now worked

```python
import pathlib

import numpy as np
from faster_whisper import WhisperModel
from loguru import logger


def fw(waveform: np.ndarray | str):
    # model_size_or_path: Size of the model to use (tiny, tiny.en, base, base.en,
    #  small, small.en, medium, medium.en, large-v1, large-v2, or large), a path to a converted
    #  model directory, or a CTranslate2-converted Whisper model ID from the Hugging Face Hub.
    #  When a size or a model ID is configured, the converted model is downloaded
    #  from the Hugging Face Hub.
    logger.debug("Starting fw")
    model_size = "small.en"
    model = WhisperModel(model_size, compute_type='float32')

    segments, info = model.transcribe(waveform, language="en")

    print(
        "Detected language '%s' with probability %f"
        % (info.language, info.language_probability)
    )

    for segment in segments:
        print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
    logger.debug("Finished fw")


if __name__ == '__main__':
    infile = pathlib.Path('~/Dropbox/resources/jfk.wav').expanduser()
    print(infile)
    fw(infile.as_posix())
```

**Comment by KoStard** [comment]
I found this issue while getting SIGSEGV from `simpleaudio`, and changing python version to 3.10.* solved the issue for me. Thanks for sharing!
