### ISSUE TITLE
CUDA + fp16 + windows, faster on Large-v1 than on Medium ?

### ISSUE THREAD

**Issue by ExtReMLapin** [SYSTRAN/faster-whisper#172]
Hello, I ran some benchmarks on models on a RTX 2070 and I end up with the following results :

```txt
 Medium GPU cuda float16 | file 874 seconds : 114 seconds working
 Large GPU cuda float16 | file 874 seconds : 107 seconds working
```

Any idea why it's faster on Large-v1 ?

**Comment by guillaumekln** [comment]
I would guess that the medium model triggers the "temperature fallback" for your audio file. In this case the transcription speed is reduced.

Can you try again with `temperature=0` to disable the temperature fallback?

**Comment by ExtReMLapin** [comment]
New results

```txt
temperature 0 =  Medium GPU cuda float16 | file 874 seconds : 90 seconds working
temperature 0 =  Large GPU cuda float16 | file 874 seconds : 99 seconds working
```

**Comment by palladium123** [comment]
I benchmarked my RTX 3090 + 7920X using a 24 min video:

Medium: 117.4s, large 123.06s

A 5% difference.

This is with beam_size=10. With beam_size = 1, it was 66.65s (large-v2) and 47.24s (medium).
