### ISSUE TITLE
Stuck End when recognizing long video

### ISSUE THREAD

**Issue by zx3777** [SYSTRAN/faster-whisper#191]
win10 gpu faster-whisper

When I use it for slightly longer audio with long gap with no speech, don't use VAD, when transcribing, sometimes it gets stuck and just won't move anymore, or it gets stuck for a long time and then ends abruptly. The dialogue after the jam is not recognized, and the timeline for outputting subtitles only goes up to the time of the jam. Instead of repeating words. after getting stuck, nothing is output in srt file

For example, this mp3 file：https://cyberfile.me/6h1c ，use for "medium/korean", no vad, it will stuck at a certain time almost evertime.

When I use the original whisper to recognize the same audio and sometimes it gets stuck, but it will continue after a while and Never had a situation like the above.

I don't want to use VAD because the recognition time will be longer.

sorry for my English.

**Comment by guillaumekln** [comment]
Can you try setting `temperature=0` and see if it makes a difference?

**Comment by vizsatiz** [comment]
Did the fix work ?
