### ISSUE TITLE
word_level timestamps are 00:00 

### ISSUE THREAD

**Issue by Ar770** [SYSTRAN/faster-whisper#338]
Sometimes (I couldn't find a certain pattern, it seems to happen randomly during the process) I get things like:
![image](https://github.com/guillaumekln/faster-whisper/assets/77382661/d9294383-9c3b-48ef-b1ba-b035fc169ee9)

Words without actual timing (they are not hallucinations of Whisper, they are said in the audio)
What can cause it and how to avoid? 
Thanks.

**Comment by Purfview** [comment]
Can you share a sample of your audio?

**Comment by Ar770** [comment]
Sure, I'm not able to upload audio files, but I was trying on https://www.youtube.com/watch?v=vk4btcrVTEU
I was trying a few times, and it happened every run.

**Comment by Purfview** [comment]
I couldn't reproduce it:

![image](https://i.imgur.com/ekn955L.png)

I used whisper-faster from there: https://github.com/Purfview/whisper-standalone-win

`whisper-faster.exe "D:\video.aac" --language=he --model=medium --vad_filter=False --compute_type=float32`

Audio sample and result: https://we.tl/t-KXSGRQBl2D

**Comment by Ar770** [comment]
Thank you for your help!
I was using a fine-tuned whisper model that I convert using ct2 as described here [README.md](https://github.com/guillaumekln/faster-whisper#model-conversion)

**Comment by Purfview** [comment]
Btw, there is posted similar issue: https://github.com/guillaumekln/faster-whisper/issues/321

**Comment by Purfview** [comment]
No idea.
Did you checked if that model works correctly before transformation?

**Comment by Ar770** [comment]
I came across this:
https://gist.github.com/hollance/42e32852f24243b748ae6bc1f985b13a
Maybe it is related?

**Comment by Ar770** [comment]
@guillaumekln thank you. 
Any advice what can we do about it?
"This may or may not work well depending on the fine-tuned model." - what it depends on?

**Comment by Ar770** [comment]
If I'll be able to get the alignment_headsof my specific fone-tuned model, how can I use them with faster-whisper? Can it improve?

**Comment by guillaumekln** [comment]
> "This may or may not work well depending on the fine-tuned model." - what it depends on?

I don't work with fine-tuned models that's why I don't know how well the default behavior is working.

> If I'll be able to get the alignment_heads of my specific fine-tuned model, how can I use them with faster-whisper?

You can simply edit `config.json` in the converted model directory and change `alignment_heads`. It is a list of attention heads where each head is referenced as `[layer index, head index]`.

**Comment by Ar770** [comment]
Who ever comes across this problem, it seems that keeping the original alignment_heads of the base model that was fine-tuned, give much more reliable timestamps.
