### ISSUE TITLE
Suggestions for improving real-time performance?

### ISSUE THREAD

**Issue by xoxfaby** [SYSTRAN/faster-whisper#348]
My particular use case requires me to have access to the transcription of a fully uttered sentence as quickly as possible, as it is being uttered. 

Are there any optimizations I can make to how I use faster-whisper that will benefit this?

Currently I'm detecting the speech and once it is finished, I give the whole thing to faster_wisper to transcribe. This is problematic because if it's a long sentence, I have to wait until the end to begin processing the beginning. Is there some reasonable way I can feed the beginning into faster_whisper before the rest of the sentence is done, without sacrificing accuracy? 

Since my understanding of the model is limited, I'm unsure if I'm missing something more obvious to improve this, like I don't know if the model even technically needs the whole thing to begin processing or if it could do the work as it comes in, in a way that just isn't done normally since it's not a concern if you're loading data at the rate it can be read, rather than the rate it is spoken. 

Would love any input on this.

**Comment by phineas-pta** [comment]
u can inspire from various repo shared in openai/whisper#2

**Comment by jnhck** [comment]
You do not necessarily need to wait for a sentence to finish to start transcribing. You could also start with a shorter sequence and then when more is available send more afterwards. Obviously the accuracy will get higher as time goes on and the sentence becomes more complete, but even before you can get good results (at least while using the largest model).
