### ISSUE TITLE
Question about compute evaluation metric 

### ISSUE THREAD

**Issue by DuyTa506** [SYSTRAN/faster-whisper#415]
Hi there , i'm really excited to your repo , but i have a question , after quantized , how did we calculate the WER metric ? 
Will it different from whisper base model or just load the same architechture but in lower precision floating-point ?

**Comment by guillaumekln** [comment]
I'm not sure to understand the question. Are you asking how to compute the WER score?

**Comment by DuyTa506** [comment]
i'm trying to calculate the wer metric , running time on this repo and huggingface model , but it's seem the running time on this repo take so much more than the other version, i dont know why . The model run on faster-whisper was quantized to int8_float16 type. Is that the reason?

**Comment by guillaumekln** [comment]
So is the issue the running time difference between faster-whisper and the Hugging Face model?

Please post the code you are using to run faster-whisper and the Hugging Face model.
