### ISSUE TITLE
FeatureExtractor consumes a lot of cpu resources

### ISSUE THREAD

**Issue by Emma-Miao** [SYSTRAN/faster-whisper#419]
I find that faster-whisper consumes a lot of cpu resources during "mel_spec = filters @ magnitudes" in FeatureExtractor class, maybe i do something wrong?  Appreciate it if you can answer @guillaumekln

**Comment by guillaumekln** [comment]
What do you mean by CPU resources here? Memory usage? CPU utilization? Threads number?

Note that this line is multiplying 2 matrices with Numpy.

**Comment by Emma-Miao** [comment]
> What do you mean by CPU resources here? Memory usage? CPU utilization? Threads number?
> 
> Note that this line is multiplying 2 matrices with Numpy.

CPU utilization

**Comment by guillaumekln** [comment]
How long is your audio file?

**Comment by Emma-Miao** [comment]
Sorry for the late. Firstly, the answer to your question is that the shape of our magnitudes in "mel_spec = filters @ magnitudes" is (201, 3144). Secondly, I tried to replace the faster-whisper's feature-extractor method to whisper's original torch implementation and the cpu utilization dropped from around 2000 to around 200, which confused me a lot. Besides, I wonder why faster-whisper implements the feature extraction algorithm instead of using whisper's original torch implementation. Thanks a lot!

**Comment by guillaumekln** [comment]
Even if the feature extraction is not the most efficient code, it should still be much faster than the actual transcription. Isn't it the case here?

> Besides, I wonder why faster-whisper implements the feature extraction algorithm instead of using whisper's original torch implementation.

Simply because we don't want to add PyTorch as a direct dependency.
