### ISSUE TITLE
Repeated Word Issue In Silent Parts

### ISSUE THREAD

**Issue by makoto-toyouke** [SYSTRAN/faster-whisper#436]
When there is a prolonged silent part in the middle, a certain specific word is repeatedly outputted continuously, and even when the conversation begins, that repeated word is still outputted, and after a while, it recovers. I am using it as follows:

`model.transcribe(new_file_path, language="ja", condition_on_previous_text=False, beam_size=5, vad_filter=True, vad_parameters=dict(min_silence_duration_ms=500))`

**Comment by guillaumekln** [comment]
Are you using the latest version?

**Comment by makoto-toyouke** [comment]
Of course, I use the latest version. It seems that it is not always occurring under the condition that it is precisely the silent part. I think it tends to repeat the same text at times when I am stuck on a word and am making unspoken sounds.

**Comment by guillaumekln** [comment]
Is it possible for you to share the input audio file?

**Comment by makoto-toyouke** [comment]
I'm sorry, I can't do that due to the high confidentiality of personal information and other sensitive data.

To add more information, adjusting the value of min_silence_duration_ms changes the locations where the error of repeating a specific word occurs. So far, we have not observed this issue in short videos. However, when attempting to transcribe a video that is about 4 hours long, the error tends to occur in about 3 places.

That's all the information I can provide.
