### ISSUE TITLE
Performance Degradation When Running Multiple Jobs in Parallel on a Single GPU

### ISSUE THREAD

**Issue by recog-arch** [SYSTRAN/faster-whisper#441]
I am facing a performance degradation issue when attempting to run multiple jobs in parallel on a single GPU. 

I have a GPU with 15GB of memory, and each of my inference jobs requires approximately 3GB of GPU memory. When running these jobs sequentially, each job takes around 40 seconds to complete. However, when I run two jobs in parallel, each creating a different model, I notice that both jobs take significantly longer to finish (around 80 seconds each).

Running two jobs in parallel indeed increases the GPU memory usage to around 6GB (3GB per job), as expected.
However, the execution time of each individual job doubles when running in parallel, even though the GPU resources are being utilized.

I suspect that this degradation in performance might be due to GPU interference or contention, where the two jobs are competing for resources such as GPU compute units, and bandwidth. This contention could lead to inefficiencies in memory management, data transfer, and resource allocation.

I am reaching out to the community to gather insights and potential solutions for this issue. If you have experience with GPU parallelism, memory optimization, or resource management, your expertise would be greatly appreciated.

**Additional Information:**

GPU: Tesla T4
Inference Jobs: Audio file of ~6 minutes being transcribed with large-v2 Whisper model using int8_float16 compute type.

I look forward to any insights or suggestions that could help me address this issue and improve the overall performance of running multiple inference jobs in parallel on a single GPU. Thank you in advance for your assistance!

**Comment by phineas-pta** [comment]
#140

**Comment by recog-arch** [comment]
> #140

Thank you for providing the link. After conducting further research on this matter, it appears that the prevailing solution to the problem I described involves the addition of more GPU devices. It seems that attempting to run multiple models concurrently on a single GPU may not yield the result I would expect.

Could you please confirm whether my understanding is right?

**Comment by olegcm** [comment]
What would be the suggested way of parallelization? Use multiple GPUs?
In case of endpoint it's better to use one worker with multiple threads which loads the model to all available GPUs
or multiple workers each one uses one GPU exclusively?

By the way we didn't see much difference in processing speed between A6000, A100 and RTX 4090.

**Comment by guillaumekln** [comment]
> What would be the suggested way of parallelization? Use multiple GPUs?

Yes, using multiple GPUs could achieve near linear scaling.

> In case of endpoint it's better to use one worker with multiple threads which loads the model to all available GPUs
or multiple workers each one uses one GPU exclusively?

I think both are valid and I can't immediately say which one would be better.

faster-whisper provides a way to use multiple GPU with multiple threads in a single Python process. You can load the model on multiple GPUs with `device_index=[0, 1, 2, 3]` and then call `model.transcribe` from multiple Python threads to run transcriptions in parallel. See also #100.

**Comment by DinnoKoluh** [comment]
@guillaumekln The [question](https://github.com/collabora/WhisperLive/issues/250) I raised at whisper-live repository might be interesting regarding this issue and faster-whisper in general.
