### ISSUE TITLE
Get alternatives for each segment

### ISSUE THREAD

**Issue by Ar770** [SYSTRAN/faster-whisper#444]
Hi
I was wondering if it would be possible to return for each segment more than one prediction?

**Comment by phineas-pta** [comment]
#333

**Comment by guillaumekln** [comment]
By default the decoding is running a beam search which can return multiple predictions. However, the segments lengths are defined by the predictions themselves. So the different predictions could have a different segments structure which can not be aligned into alternatives.

On the other hand, it could be possible to return the alternatives when using `without_timestamps=True`. In that case all segments have a fixed 30-second duration.
