### ISSUE TITLE
help  Unknown cover type: 0x1.

### ISSUE THREAD

**Issue by lilinrestart** [SYSTRAN/faster-whisper#451]
When I run to this code segment, info=model. transfer (path, beam_size=5). The program is stuck (Unknown cover type: 0x1
）And it seems like downloading something, what's going on, and sometimes it can run normally.
![image](https://github.com/guillaumekln/faster-whisper/assets/140720825/314c2f0a-8d58-42c5-ad09-7a48e6ed6aaf)

**Comment by guillaumekln** [comment]
This looks like an error from your audio file. You can probably ignore this message.

Is the program actually stuck or does it just take a long time to run? The method `model.transcribe` does not download anything.

**Comment by lilinrestart** [comment]
> 这看起来像是您的音频文件中的错误。您可能可以忽略此消息。
> 
> 程序实际上是卡住了还是只是需要很长时间才能运行？该方法`model.transcribe`不下载任何内容。

Actually, it takes a long time to run, maybe a few minutes, maybe an hour

**Comment by lilinrestart** [comment]
> 这看起来像是您的音频文件中的错误。您可以忽略此消息。
> 
> 程序实际上是卡住了还是只需要很长时间才能运行？该方法`model.transcribe`不下载任何内容。

So how can I determine if there is a problem with this audio and video? In fact, I input MP4

**Comment by lilinrestart** [comment]
> 这看起来像是您的音频文件中的错误。您可能可以忽略此消息。
> 
> 程序实际上是卡住了还是只是需要很长时间才能运行？该方法`model.transcribe`不下载任何内容。

I found that when the program got stuck, but if my download speed increased to 100m, I could continue running quickly. When the download speed was only 10m, it would take a long time. My videos are read through remote URLs, with each video length not exceeding 5 minutes. Could it be because you are downloading the video? But the download won't take more than an hour, and I don't quite understand what the problem is now

**Comment by guillaumekln** [comment]
Can you post the code you are running and show where it is taking the most time?
