### ISSUE TITLE
How to output longer segments?

### ISSUE THREAD

**Issue by DONAMO-163** [SYSTRAN/faster-whisper#452]
Hello. I am using faster-whisper to create meeting minutes.
I am mainly transcribing Japanese, but the segments are output in smaller segments as shown below.(Not the actual meeting minutes, but a segment like this.)
```
[ 64m18.91s > 64m20.91s]それぞれの
[ 64m20.91s > 64m22.91s]議論を
[ 64m22.91s > 64m24.91s]もっと
[ 64m24.91s > 64m26.91s]効率的に
[ 64m26.91s > 64m28.91s]実施したい
[ 64m28.91s > 64m30.91s]というような
[ 64m30.91s > 64m32.91s]ことを
[ 64m32.91s > 64m34.91s]考えています
```
In other discussions, word-by-word transcription methods were discussed, but I could not find a way to make the segments longer.
Up to the segment of Japanese speech, (similar to English text, up to a period?) Is there an option or method to output one segment longer?

using version : faster-whisper 0.7.1

**Comment by guillaumekln** [comment]
There is no option to control the segment length. faster-whisper returns the segments as they are generated by the Whisper model.

However, you could probably implement some sort of postprocessing that concatenates multiple segments based on your own rules.

**Comment by zx3777** [comment]
> There is no option to control the segment length. faster-whisper returns the segments as they are generated by the Whisper model.
> 
> However, you could probably implement some sort of postprocessing that concatenates multiple segments based on your own rules.

When I tested the same sample audio, the faster-whisper sentences were actually shorter than the original whisper would have recognized.

**Comment by guillaumekln** [comment]
@zx3777 If you want us to look into this, please post the audio sample you are testing.

**Comment by archive-r** [comment]
Do you use VAD in faster-whisper?

**Comment by zx3777** [comment]
> 

no

**Comment by arubittu** [comment]
> There is no option to control the segment length. faster-whisper returns the segments as they are generated by the Whisper model.
> 
> However, you could probably implement some sort of postprocessing that concatenates multiple segments based on your own rules.

so essentially words are streamed right
