### ISSUE TITLE
Playing with faster-whisper audio segmentation. How does it work ?

### ISSUE THREAD

**Issue by Lorenzoncina** [SYSTRAN/faster-whisper#456]
I'm trying to controll the chunk_lenght of the input audio file as suggested in [#171 ](https://github.com/guillaumekln/faster-whisper/issues/171). The idea is to set it to 10 seconds, which is the lenght of the audio files I used to fine-tuned whisper large v2 with the transformer library. This idea came from this interesting article about decoding long audio file with Whisper and Hugging Face Api where the play with the chunk_lenght_s parameter: [decoding long audio files with HF api](https://huggingface.co/blog/asr-chunking)
I'm seeing a weird behaviour thoug, expecially two things:

1.  Inference runned with the same fine-tuned model mentioned earlier using Hugging Face API (pipeline) and faster-whisper lead to different results. For both I set the chunk_lenght=10 seconds. Hugging Face API (as explained  [here](https://huggingface.co/blog/asr-chunking) ) works very well, providing  a correct output, while faster-whisper shows a lot of deletion errors at segments boundaries. This led me to ask if the segmentation of long audio files used by faster-whisper  is the same used by Hugging Face API. I went through the source code and it's not 100% clear how long audio files are segmented by faster whisper.
2. I noticed that the output provided by fatser-whisper for the same audio file changes by changing combination of chunk_lenght and hop_length of the feature extractor. In particular, the are some combination wich are allowed, otheres lead to errors. For example by default chunk_lenght=30 and hop_length=160 is very bad for my fine tuned model, instead chunk_lenght=1 and hop_length=80 is way better, giving a transcription almost correct (a part from deletion error at segment boundaries). Instead, If I seat for example chunk_length=10, hop_length=50 I get the following error:
`File "/home/smtadmin/faster_whisper_venv_30_sec_chunk/lib/python3.8/site-packages/faster_whisper/transcribe.py", line 887, in restore_speech_timestamps
    for segment in segments:
  File "/home/smtadmin/faster_whisper_venv_30_sec_chunk/lib/python3.8/site-packages/faster_whisper/transcribe.py", line 400, in generate_segments
    encoder_output = self.encode(segment)
  File "/home/smtadmin/faster_whisper_venv_30_sec_chunk/lib/python3.8/site-packages/faster_whisper/transcribe.py", line 577, in encode
    return self.model.encode(features, to_cpu=to_cpu)
ValueError: Invalid input features shape: expected an input with shape (1, 80, 3000), but got an input with shape (1, 80, 3200) instead
`

**Comment by guillaumekln** [comment]
> This led me to ask if the segmentation of long audio files used by faster-whisper is the same used by Hugging Face API.

faster-whisper implements the same strategy as openai-whisper, which is quite different than the technique used in HF. The strategy is described in section 3.8 of the [Whisper paper](https://arxiv.org/pdf/2212.04356.pdf). It relies on accurate prediction of timestamp tokens. For fine-tuned models, you may want to try disabling timestamp tokens with `without_timestamps=True`.
