### ISSUE TITLE
convert pytorch model to ctranslate2 model stops because of the tokenizer file problem

### ISSUE THREAD

**Issue by ILG2021** [SYSTRAN/faster-whisper#464]
I have finetune whisper by transformer and pytorch. And after execute those steps below,
```
processor.save_pretrained(training_args.output_dir)
trainer.save_model(output_dir)
```
all of the files generated are:
```
preprocessor_config.json
tokenizer_config.json
special_tokens_map.json
added_tokens.json
vocab.json
merges.txt
normalizer.json
config.json
generation_config.json
pytorch_model.bin
training_args.bin
```
when i convert the model by :
`ct2-transformers-converter --model ./whisper-large-v2-multi --output_dir ./whisper-large-v2-multi-ct2-- --copy_files tokenizer.json --quantization float16 --force`

it stops and said need tokenizer.json file. I copy it from the openai/whipser-large-v2 on huggingface, and then another error:
`
ValueError: Wrong index found for <|0.00|>: should be 50257 but found 50364.
`
I found index of <|0.00|> is 50364 in the file added_tokens.json. it is very different with the one in openai/whisper-large-v2. 
it is very confuse for me. Can i save tokenizer file when the finetune is finish? and why the index error happend?

in addition, when i overlay the added_tokens.json file by the orginal one in openai/whisper-large-v2, the convert can be success. but i think it will affect the model. so how to deal with the problem?

After convert, it doesn't generate vocabulary.txt file which is need for inference later.

**Comment by Lorenzoncina** [comment]
Are you sure you copied the correct tokenizer from pre-trained models? If you copied the one from large v2, I guess you fine-tuned large v2 as well

**Comment by ILG2021** [comment]
i mean can it be generated automatically, not by copy.

**Comment by Lorenzoncina** [comment]
Not sure but I just copied tetokenizer.json file from the pre-trained folder on Huggin Face and it worked well the conversion.
Maybe @guillaumekln can give you a better explanation

**Comment by guillaumekln** [comment]
I don't know how you fine-tuned the model. Maybe you updated the vocabulary in this process?

Note that the error message you reported in the first post is coming from Transformers, not CTranslate2. Before conversion you should make sure that the tokenization configuration is present and consistent with your model.

**Comment by omarelb** [comment]
It would be nice to add this in the README, or add a flag to the `ct2-transformers-converter` script such as `--base-model openai/whisper-medium`, that then downloads the appropriate files (`vocab.json`, `tokenizer.json`, etc.) when necessary. I might make a PR for this if necessary :)
