### ISSUE TITLE
adding initial_prompt is changing the segment duration

### ISSUE THREAD

**Issue by abdulnim** [SYSTRAN/faster-whisper#474]
For the same audio without inital_prompt, the segments are smaller and more accurate
[0.00s -> 6.20s] text ...
[6.30s -> 10.80s] text ...
[11.30s -> 13.80s] text ...
[13.90s -> 18.60s] text ...
[20.60s -> 23.80s] text ...
[27.88s -> 30.88s] text ...
[31.48s -> 36.98s] text ...
[37.08s -> 39.08s] text ...
[39.98s -> 42.88s] text ...
[44.48s -> 50.68s] text ...
-----
But if I provide some words as inital_prompt the the segments become bigger and inaccurate.
[0.00s -> 31.38s]
[31.58s -> 39.06s]
[40.06s -> 50.54s]
[52.34s -> 56.54s]

**Comment by guillaumekln** [comment]
The initial prompt can change both the segments duration and text. This is how the Whisper model is working. You would probably get a similar result with openai-whisper.

**Comment by abdulnim** [comment]
the result of whispex looks better when comparing prompt-provided transcription without providing an initial prompt. 
i am not sure if whisperx is re-calculating the segment time stamps in the alignment but will dig deep to see how is it keeping the duration same.

**Comment by kaixxx** [comment]
I ran into the same problem and did some experimentation. In my case the problem was that my initial prompt contained two sentences. As a result, whisper was always giving me two-sentence-segments back. Once I reformulated the prompt so that it contained only one sentence, I got much shorter segments.
