### ISSUE TITLE
How to set command to remove output timestamps?

### ISSUE THREAD

**Issue by tomkuo1124** [SYSTRAN/faster-whisper#509]
Dear all, 
I have read faster-whisper help file but can't find a way to remove timestamps, I recorded a voice file and try to output as txt file without timestamps. 
Below is command I used:
Use whisper-faster.exe r153
whisper-faster.exe "C:\Users\kuoto\Documents\Sound Recordings\Recording.m4a"  --task=transcribe --output_format=txt  --language=Chinese --model=large-v2

Could you please help to share a way to output text file and no timestaps?
Thanks for your kindly support.

![image](https://github.com/guillaumekln/faster-whisper/assets/137477635/0f5e219b-b40f-4e4a-8554-5e132e1a441d)

**Comment by phineas-pta** [comment]
wrong repo, your question should be in https://github.com/Purfview/whisper-standalone-win

**Comment by Purfview** [comment]
`--output_format=text`

**Comment by Soeroah** [comment]
> `--output_format=text`

This no longer appears to be working, my text file output includes timestamps
