### ISSUE TITLE
Can faster-whisper support TPU?

### ISSUE THREAD

**Issue by ILG2021** [SYSTRAN/faster-whisper#518]
Kaggle and colab both supply TPU, it is much faster than T4. So can faster-whisper support it?

**Comment by gl-jkeys** [comment]
We would be interested in TPU acceleration as well.

**Comment by ILG2021** [comment]
kaggle is v3-8 physical device, colab is cloud tpu.

**Comment by rpurdel** [comment]
AWS inferentia would also be a nice plus
