### ISSUE TITLE
Support for Distil-Whisper

### ISSUE THREAD

**Issue by sanchit-gandhi** [SYSTRAN/faster-whisper#533]
Hey @guillaumekln! Thanks for this fantastic resource. We're looking at supporting the [Distil-Whisper](https://github.com/huggingface/distil-whisper) checkpoints in faster-whisper.

The checkpoints are fairly easy to convert: we just pin the number of decoder layers to 2 always, and load the 32 encoder layers.

For inference, we found a chunk length of 15-20s to be optimal for WER performance of the distilled model, see Table 23 of the [paper](https://arxiv.org/abs/2311.00430):

<img width="858" alt="Screenshot 2023-11-01 at 17 05 58" src="https://github.com/guillaumekln/faster-whisper/assets/93869735/ea4ea9b6-465b-4344-8663-1dc92abcf6b2">

 Would you be open to a PR allowing the user to specify the chunk length and also the maximum generation length? This would enable full support of Distil-Whisper in faster-whisper!

**Comment by Axbon** [comment]
This would be amazing, one step closer to something that feels realtime*ish

**Comment by ozancaglayan** [comment]
Is the distilled `large-v2` model still multilingual or does it lose that attribute due to how distilling was done?

**Comment by AmgadHasan** [comment]
> Is the distilled `large-v2` model still multilingual or does it lose that attribute due to how distilling was done?

It was trained on English audio only so it most probably lost its multilingual capabilities.

**Comment by guilhermehge** [comment]
> Is the distilled `large-v2` model still multilingual or does it lose that attribute due to how distilling was done?

From their repo: "Note: Distil-Whisper is currently only available for English speech recognition. Multilingual support will be provided soon."

**Comment by archive-r** [comment]
Waiting for a multilingual model for this task. Looking forward to it

**Comment by martinkallstrom** [comment]
Subscribing for updates!

**Comment by silvacarl2** [comment]
can't wait to test it, this will be awesome.

**Comment by WikiLucas00** [comment]
hi @sanchit-gandhi. FYI, @guillaumekln's account seems inactive since September, which correlates with the moment [he moved from his former company](https://community.libretranslate.com/t/ctranslate2-dev-starting-job-as-machine-learning-engineer-at-apple/729). I don't know if he plans to continue maintaining this repo or if other users such as OpenNMT devs (cc @vince62s @homink @nguyendc-systran) have ownership on the repo or forked it. Maybe consider forking it yourself under HF's Github namespace?

**Comment by guillaumekln** [comment]
Hi, I confirm that I'm no longer actively maintaining this repo but other people can still make it move forward. Please ping @nguyendc-systran to merge changes in faster-whisper. For anything related to CTranslate2, please ping @vince62s.

**Comment by BBC-Esq** [comment]
> Hi, I confirm that I'm no longer actively maintaining this repo but other people can still make it move forward. Please ping @nguyendc-systran to merge changes in faster-whisper. For anything related to CTranslate2, please ping @vince62s.

Great job on Ctranslate2 and faster-whisper, glad I came across it awhile ago now...and good luck in the future.

**Comment by WikiLucas00** [comment]
FYI, distil-whisper should now be supported by CTranslate2: https://github.com/OpenNMT/CTranslate2/releases/tag/v3.21.0

We "just" need to adapt faster-whisper in order to have faster-distil-whisper :)

**Comment by metame-none** [comment]
FYI, I made a PR: https://github.com/guillaumekln/faster-whisper/pull/557 to make it compatible with distil-whisper, hope it helps.
