### ISSUE TITLE
Typo in language specification 'jw'?

### ISSUE THREAD

**Issue by DKWoods** [SYSTRAN/faster-whisper#540]
In the file tokenizer.py, a tuple called _LANGUAGE_CODES declares a list of supported languages.

This variable includes the language code 'jw' which is not, as far as I can tell, an ISO-defined language.  (It is used with a language tool for Jehovah's Witnesses, the internet tells me.)  I suspect this is a typo for 'jv' or Javanese.  But I'm a bit out of my depth here, so am seeking input from those more experienced with languages and with faster_whisper's model dependencies.

According to a 2001 article at https://xml.coverpages.org/iso639a.html, on the topic of "Changes from ISO 639:1988 to ISO 639-1:2001", "In addition, ISO 639:1988 contains one error. The identifier for Javanese is rendered as "jw" in table 1, while it is correctly given as "jv" in the other tables."  This may explain the issue.

If you can confirm this interpretation, I will happily submit a PR.  Or am I best off using the not-technically-correct language code?

**Comment by stillmatic** [comment]
matches upstream implementation here: https://github.com/openai/whisper/blob/main/whisper/tokenizer.py#L108

**Comment by JakobHavtorn** [comment]
Just came across this issue too. I use `langcodes` to parse BCP 47 language codes which are the same used by Whisper (almost at least).

This is my parser:

```python
from langcodes import Language

def parse_language_code(code) -> dict[str, str]:
    """Parse a BCP 47 language code into its components."""
    try:
        lang = Language.get(code)  # This validates the BCP 47 code
    except ValueError:
        raise ValueError(f"Invalid BCP 47 language code: {code}")

    if not lang.is_valid():
        raise ValueError(f"Language code {code} gave invalid language {lang}")

    return {
        "language": lang.language if lang.language else None,
        "script": lang.script if lang.script else None,
        "region": lang.region if lang.region else None,
        "variants": lang.variants if lang.variants else None,
    }
```

Running the below test fails due to the discrepancy between `jw` and `jv` described above.

```python
from faster_whisper.tokenizer import _LANGUAGE_CODES

def test_exact_match_language_code(self):
    for language in _LANGUAGE_CODES:
        assert parse_language_code(language)["language"] == language
```

I.e.

```python
AssertionError: assert 'jv' == 'jw'
  
  - jw
  + jv
```
