### ISSUE TITLE
is faster-whisper.cpp possible?

### ISSUE THREAD

**Issue by rawwerks** [SYSTRAN/faster-whisper#551]
is faster-whisper.cpp possible (without any python)?

from a quick review of https://github.com/OpenNMT/CTranslate2/, it is hard for me to tell if it is possible to implement entirely with cpp, which would enable iOS apps such as https://github.com/Saik0s/Whisperboard to use faster-whisper (see: https://github.com/Saik0s/Whisperboard/issues/24)

**Comment by westhecool** [comment]
Doesn't this already exist here? https://github.com/ggerganov/whisper.cpp

**Comment by rawwerks** [comment]
my understanding was that this repo is accelerating https://github.com/ggerganov/whisper.cpp with https://github.com/OpenNMT/CTranslate2/ , but maybe the whisper.cpp repo now already incorporates the speed advancements that are available here?

**Comment by phineas-pta** [comment]
they are different projects: `faster-whisper` use `ctranslate2` backend, `whisper.cpp` use `ggml` backend

`ctranslate2` has c++ binding so should be possible to write your own c++ code but unlikely to be compatible with `whisper.cpp`
