### ISSUE TITLE
faster_whisper with Batching

### ISSUE THREAD

**Issue by souvikqb** [SYSTRAN/faster-whisper#558]
Has anyone tried batch processing using faster_whisper? 

By batch processing, I mean defining a batch_size and chunk_length which can help in a greater inference speed.

Something similar to whisper transformers pipeline - https://huggingface.co/openai/whisper-large-v3

If so pls redirect me to that resource/repo

**Comment by Purfview** [comment]
Dupe. You opened same issue few days ago: https://github.com/guillaumekln/faster-whisper/issues/553

**Comment by AlbieRWang** [comment]
> Dupe. You opened same issue few days ago: #553

but i can't load ct2 model with transformer pipeline,is there anyway else?
