### ISSUE TITLE
insanely faster whisper repository bold claims?

### ISSUE THREAD

**Issue by BBC-Esq** [SYSTRAN/faster-whisper#563]
Has anyone seen this repository?  [https://github.com/Vaibhavs10/insanely-fast-whisper](https://github.com/Vaibhavs10/insanely-fast-whisper)

It makes the incredulous claims that it's approximately 6x times faster than faster-whisper.  I checked the github repo and they don't make the sourcecode available (even though there's a "src" folder), but there is a library on Pypi that you can install named "insanely-fast-whisper" located [https://pypi.org/project/insanely-fast-whisper/](https://pypi.org/project/insanely-fast-whisper/).

Apparently, you can use it either with or without FlashAttention2...I couldn't get FlashAttention2 to install...

Does Faster-Whisper use flashattention2?
Does anyone know what the backend is...is it using Faster-Whisper per chance...the only difference being the "batch_size" parameter that allows them to process more segments of the audio file at once?

Even when I change  the batch_size to 1, however, it still runs faster than faster-whisper APPROXIMATELY 2X, NOT 6X LIKE IT CLAIMS.

My test was as follows...

Using Faster-Whisper...
```large-v2``` model in float32 format (in ctranslate2 format of course)

For "insanely-faster-whisper" I transcribed the same audio file...and here's the relevant portion of my script:

```
# Initialize the pipeline
pipe = pipeline("automatic-speech-recognition",
                "openai/whisper-large-v2",
                torch_dtype=torch.float32,
                device="cuda:0")

pipe.model = pipe.model.to_bettertransformer()

# Process the audio file
outputs = pipe("[REMOVED PATH TO FILE FOR PRIVACY REASONS",
               chunk_length_s=30,
               batch_size=1,
               return_timestamps=True)
```

Again, even though the batch size was "1" it was still approximately 2x as fast.  Now, I didn't get a chance to test accuracy but...Anyone know what this library is based on???

**Comment by BBC-Esq** [comment]
If anyone's interested, here are the responses I received from the repo admin...Feel free to close this issue out, but preferably leave it open for awhile to give people a chance to comment on how we might make Ctranslate2 better (perhaps Flash Attention v2??):

[https://github.com/Vaibhavs10/insanely-fast-whisper/issues/51](https://github.com/Vaibhavs10/insanely-fast-whisper/issues/51)

**Comment by BBC-Esq** [comment]
Turns out they do use a beam size of 1 and batching...See my above discussion with them.  Ctranslate2's default beam size is 5 I believe and no batching so....Likely not faster than Ctranslate2...With that being said, is there any interest in introducing batching and/or flash attention v2?

**Comment by blackpolarz** [comment]
I actually tested flash attention v2 on my end, running on a 3080 12gb, no batching with beam size of 1. It was running on FP16, whisper-v3 model, and the task is translate. Unfortunately, my results for flash attention v2 were slightly slower than using faster-whisper with beam size of 5, best of 3, FP16. 
Note that I only start the timer after the entire model is loaded and end the timer as soon as the model is done inferencing. 
The accuracy were similar, with the same problem of hallucination at times. That said using whisper will require the setting up of ffmpeg which is a little troublesome for users using Windows.

**Comment by BBC-Esq** [comment]
Good point, I thought about starting the timer only after the model was loaded but the amount of testing was sufficient...even if not all-encompassing.  To me, it's impressive that Ctranslate2 performs so well still even though it's been out a lot longer than other technologies...but I'm wondering if there's a way to use newer techniques like flash attention 2 or what not...wish I was a programmer and knew how to implement it.
