### ISSUE TITLE
pcm format

### ISSUE THREAD

**Issue by wwfcnu** [SYSTRAN/faster-whisper#579]
support model.transcribe(example.pcm)?

**Comment by wwfcnu** [comment]
> any audio waveform as numpy array should work任何作为 numpy 数组的音频波形都应该有效
But when I input a file in PCM format, the load_audio function encounters an error during the ffmpeg processing

**Comment by wwfcnu** [comment]
```
subprocess.CalledProcessError: Command '['ffmpeg', '-nostdin', '-threads', '0', '-i', '/mnt/data/asr_datasets/online_audio/20231018/000000b9-7ba0-40fd-994b-a0d0b53a782d.pcm', '-f', 's
16le', '-ac', '1', '-acodec', 'pcm_s16le', '-ar', '16000', '-']' returned non-zero exit status 1.
```

**Comment by phineas-pta** [comment]
i said numpy array not pcm file

**Comment by wwfcnu** [comment]
How ffmpeg handles pcm format
