### ISSUE TITLE
New version not working on fine-tuned Whisper-large-V3 models

### ISSUE THREAD

**Issue by sproocht** [SYSTRAN/faster-whisper#582]
Hello,

Thanks for updating the package to version 0.10.0. It works fine with the default "large-v3" model. However, it does not  seem to work on my finetuned Whisper-large-V3 model. There are still some discrepancies between the finetuned model's n_mels (128) and the feature_extractor.mel_filters.shape . This leads to an error while transcribing audio files:

`ValueError: Invalid input features shape: expected an input with shape (1, 128, 3000), but got an input with shape (1, 80, 3000) instead`

I have to manually fix the issue after loading the model, using the following code:
`model.feature_extractor.mel_filters = model.feature_extractor.get_mel_filters(model.feature_extractor.sampling_rate, model.feature_extractor.n_fft, n_mels=model.model.n_mels)`

Could you please have a look?

Thanks in advance!

**Comment by ILG2021** [comment]
The pip version is still 0.9.0

**Comment by ILG2021** [comment]
I encoutered the same problem. you should update all the json files in the offical one:
https://huggingface.co/Systran/faster-whisper-large-v3/tree/main

it is different with large v2

**Comment by sproocht** [comment]
I was actually missing the **preprocessor_config.json** file during the conversion of the model with ct2-transformers-converter. The inference runs fine now.
Closing the issue now.
