### ISSUE TITLE
Is there anyway to transcribe english audio to other languages like the way original whisper -v3 does. 

### ISSUE THREAD

**Issue by furqan4545** [SYSTRAN/faster-whisper#589]
Hi, is there anyway to transcribe english audio to other languages like the way original whisper -v3 does. 
If not, could you please add support for that too. It would be such great. Thank you

**Comment by Purfview** [comment]
What is "whisper -v3"?

**Comment by furqan4545** [comment]
"whisper-large-v3"

**Comment by Purfview** [comment]
Can't you do same with "whisper-large-v2" or "faster-whisper-large-v2"?

**Comment by RuntimeRacer** [comment]
> Can't you do same with "whisper-large-v2" or "faster-whisper-large-v2"?

He probably could... But I think his question is missing a statement of what the actual problem is.

**Comment by furqan4545** [comment]
model_size = "large-v3"

model = WhisperModel(model_size, device="cpu")

# or run on GPU with INT8
# model = WhisperModel(model_size, device="cpu", compute_type="int8_float16")
# or run on CPU with INT8
# model = WhisperModel(model_size, device="cpu", compute_type="int8")

segments, info = model.transcribe("steve.mp3", beam_size=5, language='fr')

###############################
ok so for example I want to transcribe an english video to french. In original whisper from openAI I can do that by specifying language parameter but it doesn't work here the same way. even If i specify other language, it still transcribe the video in original language which is english.

**Comment by furqan4545** [comment]
@guillaumekln  any advise?

**Comment by Purfview** [comment]
> If i specify other language, it still transcribe the video in original language which is english.

Can't reproduce. It's something wrong on your end.

**Comment by furqan4545** [comment]
So you got english video transription in french ?
Can you show me the output?

**Comment by Purfview** [comment]
![Screenshot_6](https://github.com/SYSTRAN/faster-whisper/assets/69023953/db4786db-f919-4323-ab2b-ff509154b605)

**Comment by furqan4545** [comment]
u simply misused it, and somehow got lucky it output something.
##################
FYI It works very well. They might have not stated it officially. But my startup uses whisper and we use it for translation tasks as well (translation not to english but to another languages).

**Comment by Purfview** [comment]
Make sure that you have official version and use official model.

**Comment by Purfview** [comment]
Btw, found the official comment about it:

`Translating into languages other than English wasn't a part of the training objective, so that behavior may not be always reliable.`

**Comment by furqan4545** [comment]
I see, but It works well on GPU. I am facing issue only with CPU.

**Comment by furqan4545** [comment]
<img width="800" alt="image" src="https://github.com/SYSTRAN/faster-whisper/assets/50285664/bfcfaed1-53c1-4d73-86a7-bf3444b71435">

@Purfview  still same issue at my end. Are you sure you are using CPU?

**Comment by Purfview** [comment]
> I see, but It works well on GPU. I am facing issue only with CPU.

As you can see in my screenshot it run on CPU

**Comment by furqan4545** [comment]
Interesting... it's working fine for french on CPU. But not with korean lol.

**Comment by Purfview** [comment]
> Interesting... it's working fine for french on CPU. But not with korean lol.

Read: https://github.com/SYSTRAN/faster-whisper/issues/589#issuecomment-1830342596

**Comment by Purfview** [comment]
What if you use `int8_float_32` on GPU?

**Comment by furqan4545** [comment]
Let me try

**Comment by Purfview** [comment]
Wait, isn't that actually Korean in your screenshot?

**Comment by furqan4545** [comment]
yes, but it's actually wrong. It is saying korean subtitles by haejong... something weird shit. 
my original video is this.  https://www.youtube.com/watch?v=CeSAjK2CBEA

**Comment by Purfview** [comment]
Then your issue is not like you described in OP.

Your issue that you are getting hallucinations with one quantization type vs another.

**Comment by Purfview** [comment]
Anyway, hallucinations is the trademark of  `large-v3`, nothing unusual. 😆

Use `large-v2`!
