### ISSUE TITLE
any vanilla model available for ci testing?

### ISSUE THREAD

**Issue by DeoLeung** [SYSTRAN/faster-whisper#596]
we now add `tiny` into our ci pipeline, which is about 70mb large.

it will be great if there's a small enough working model for ci test, similar to those `hf-internal-testing` models

**Comment by trungkienbkhn** [comment]
Unfortunately, tiny is the smallest model. If you want to use a small model for testing, you can train your own models.
The below projects maybe helpful:
https://github.com/OpenNMT/OpenNMT-py
https://github.com/OpenNMT/OpenNMT-tf
