### ISSUE TITLE
Some bugs of guide code for large-v3 model

### ISSUE THREAD

**Issue by Thundercup** [SYSTRAN/faster-whisper#605]
When I try to run code in instruction, it returned "ValueError: Invalid model size 'large-v3', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2, large". Then I replace "large-3" with "Systran/faster-whisper-large-v3", it reported different error:  ValueError: Invalid input features shape: expected an input with shape (1, 128, 3000), but got an input with shape (1, 80, 3000) instead.

**Comment by R4ZZ3** [comment]
Did you get it to work @Thundercup? If so, how?

**Comment by Thundercup** [comment]
> Did you get it to work @Thundercup? If so, how?
you can update faster-whisper firstly, if it still report error, see https://github.com/SYSTRAN/faster-whisper/issues/547
