### ISSUE TITLE
 【HELP】Google Colab's CUDA version has been updated from 11 to 12

### ISSUE THREAD

**Issue by makoto-toyouke** [SYSTRAN/faster-whisper#623]
I have encountered an issue where Google Colab's CUDA version has been updated from 11 to 12, which is causing significant problems for me. Unfortunately, I have been unable to find a way to revert Colab back to CUDA 11 despite multiple attempts and research. I am currently facing difficulties due to this update. If possible, I would greatly appreciate any guidance on how to switch back to CUDA 11. However, if that's not feasible, I kindly request assistance in making my code compatible with CUDA 12.

**Comment by funboarder13920** [comment]
https://github.com/googlecolab/colabtools/issues/4214#issuecomment-1859155789

**Comment by makoto-toyouke** [comment]
I didn't quite understand, so I rewrote the code myself and resolved it.
