### ISSUE TITLE
How can I set faster-whisper so that the timestamp is very accurate

### ISSUE THREAD

**Issue by yumianhuli1** [SYSTRAN/faster-whisper#630]
1、I found that the time stamp of the audio is not very accurate, is there any parameter set after the time stamp becomes very accurate?
2、Is the timestamp of Whispercpp proj more accurate than this project?
Thanks!

**Comment by Purfview** [comment]
Did you use `word_timestamps=True`?

**Comment by Purfview** [comment]
> Yes, I did, but it didn't work well
Since you've used word_timestamps=True, have you never had an inaccurate timestamp?

Works pretty well for my use cases, usually it's ~accurate, but I've seen cases of the weird inaccuracies on some user samples.
If you do translation then timestamps inaccuracy is expected.

> Is the timestamp of Whispercpp proj more accurate than this project?

No.

**Comment by yumianhuli1** [comment]
> > Yes, I did, but it didn't work well
> > Since you've used word_timestamps=True, have you never had an inaccurate timestamp?
> 
> Works pretty well for my use cases, usually it's ~accurate, but I've seen cases of the weird inaccuracies on some user samples. If you do translation then timestamps inaccuracy is expected.
> 
> > Is the timestamp of Whispercpp proj more accurate than this project?
> 
> No.

Well, thank you for your feedback
