### ISSUE TITLE
Is it possible to have multi channel transcription?

### ISSUE THREAD

**Issue by edihasaj** [SYSTRAN/faster-whisper#631]
I was interested to know if that is currently possible to have multichannel support from the same audio with different microphones or different audio sources?

**Comment by trungkienbkhn** [comment]
To my knowledge, the `model.transcribe()` function only supports mono audio with single channel. But if you want to use multi channel audio, you can split your audio into multi signals then send them to the transcribe function for detection.
For plus info: https://github.com/SYSTRAN/faster-whisper/pull/97

**Comment by edihasaj** [comment]
thank you for the support
