### ISSUE TITLE
ImportError: cannot import name 'get_writer' from 'faster_whisper.utils' 

### ISSUE THREAD

**Issue by knuurr** [SYSTRAN/faster-whisper#632]
I see writer functionality from original Whisper repo is not included, judging by `utils.py` content and obviously error..

Since I'd like to save results of transcription:

- is there plan to implement this functionality form original repo?
- if not, how can I write results?

This is from my other script where I used Whisper from OpenAI, works fine.

```python
result = model.transcribe(source_path, verbose=True, language="pl", batch_size=16)

srt_writer = get_writer("srt", transcript_path)
srt_writer(result, mp3_file)
```

**Comment by Purfview** [comment]
> is there plan to implement this functionality form original repo?

I doubt that.

> if not, how can I write results?

If you wan't it working out of the box then use one of these repos:

1) Mirrors vanilla Whisper's writer -> https://github.com/Softcatala/whisper-ctranslate2

2) Vanilla Whisper's writer + lots of new options -> https://github.com/Purfview/whisper-standalone-win
But it's not for Python.
Try `--sentence` or `--standard`.

**Comment by knuurr** [comment]
I will takea look. Thanks.
