### ISSUE TITLE
error from transcribe.py <[Errno 1094995529] Invalid data found when processing input: '<none>'>

### ISSUE THREAD

**Issue by goldenbubble2023** [SYSTRAN/faster-whisper#637]
model.transcribe('name.mp3') works well, but once I replace it with a bytes audio file, transcribe crashs. Of course I followed instruction from ' Add support for passing buffers to transcribe #20 '.  buffer with _[io.BytesIO]_ before processing code.   I really need a hand.

# **the crash errors:**

-   File "\\PycharmProjects\pythonProject\streamlit\word_tts_stt.py", line 69, in whisper_stt segments, _ = model.transcribe(output, beam_size=5, language="zh", vad_filter=True,
-   File "C:\Users\Programs\Python\Python310\lib\site packages\faster_whisper\transcribe.py", line 277, in transcribe audio = decode_audio(audio, sampling_rate=sampling_rate)
-   File "C:\Programs\Python\Python310\lib\site-packages\faster_whisper\audio.py", line 46, in decode_audio
-   with av.open(input_file, metadata_errors="ignore") as container:
-   File "av\container\core.pyx", line 401, in av.container.core.open
-   File "av\container\core.pyx", line 272, in av.container.core.Container.__cinit__
-   File "av\container\core.pyx", line 292, in av.container.core.Container.err_check
-   File "av\error.pyx", line 336, in av.error.err_check
- av.error.InvalidDataError: [Errno 1094995529] Invalid data found when processing input: '<none>'

# **my code:**
```
def whisper_stt(output):
    model_size = "large-v3"
    path = r"F:\GPTS\faster-whisper\large-v3"
    model = WhisperModel(model_size_or_path=path, device="cuda", local_files_only=True)
    segments, info = model.transcribe(output, beam_size=5, language="zh", vad_filter=True,
                                      vad_parameters=dict(min_silence_duration_ms=1000))
    print("Detected language '%s' with probability %f" % (info.language, info.language_probability))
    for segment in segments:
    return segment.text

audio = audiorecorder("🎙️ Start", "🎙️ Stop", key='a1')
audio = audio.set_frame_rate(16000)
bytes_audio_data = audio.raw_data
if len(bytes_audio_data) > 0
    binaryIO_audio = io.BytesIO(bytes_audio_data)
    stt_content = whisper_stt(binaryIO_audio)
```

**Comment by trungkienbkhn** [comment]
Hello. Which python lib do you use to record ?
In my example, I used `sounddevice` lib and it worked as expected.
```python
import sounddevice as sd
import numpy as np
from faster_whisper import WhisperModel

print("Recording started")
duration = 10
sample_rate = 16000
audio_data = sd.rec(int(sample_rate * duration), samplerate=sample_rate, channels=1, dtype=np.float32)
sd.wait()
audio_data = audio_data.squeeze()
print("Recording stopped")

model = WhisperModel('tiny', device='cuda')
segments, info = model.transcribe(audio_data, word_timestamps=True)
for segment in segments:
    print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
```

**Comment by rabyunghwa** [comment]
@goldenbubble2023 Was the issue resolved? Not sure why no solution was provided whatsoever and yet they just closed this thread. I've run into a similar issue.

**Comment by MahmoudAshraf97** [comment]
We've closed it because it's stale, and this is a PyAV problem not faster whisper
