### ISSUE TITLE
Language autodetection prevents multilingual transcription

### ISSUE THREAD

**Issue by gaspardpetit** [SYSTRAN/faster-whisper#638]
Hello,

Thank you for the `CTranslate2` port of whisper. I am working on a multilingual transcription tool and would like to rely on this project for the whisper heavy-lifting. 

The current implementation makes it difficult however to deal with multiple languages spoken concurrently. In my transcriptions, these are:
- Words from multiple languages spoken within the same sentence 
- Switching language during the conversation for several sentences.

The following code is the issue:

```
        if language is None:
            if not self.model.is_multilingual:
                language = "en"
                language_probability = 1
            else:
                segment = features[:, : self.feature_extractor.nb_max_frames]
                encoder_output = self.encode(segment)
                # results is a list of tuple[str, float] with language names and
                # probabilities.
                results = self.model.detect_language(encoder_output)[0]
                # Parse language names to strip out markers
                all_language_probs = [(token[2:-2], prob) for (token, prob) in results]
                # Get top language token and probability
                language, language_probability = all_language_probs[0]

                self.logger.info(
                    "Detected language '%s' with probability %.2f",
                    language,
                    language_probability,
                )
        else:
            if not self.model.is_multilingual and language != "en":
                self.logger.warning(
                    "The current model is English-only but the language parameter is set to '%s'; "
                    "using 'en' instead." % language
                )
                language = "en"

            language_probability = 1
```

Once set, the model will either generate nonsense or translate the content. For my use case, language detection should be optional. When unset, the multilingual whisper models will transcribe from any language.   This is not always perfect, but in my case, I am performing a second pass on the speech resolving.

If you are interested in making language detection optional, I am willing to provide a PR for it.

**Comment by Purfview** [comment]
> multilingual transcription

Model doesn't support transcription of multilingual audio.

> For my use case, language detection should be optional.

It's optional. Set `language`.

**Comment by gaspardpetit** [comment]
Apologies for my confusion, you are correct! I realize now that openai-whisper applies the same logic. Thank you for taking the time to answer!
