### ISSUE TITLE
How to check if my model is properly loaded on cuda?

### ISSUE THREAD

**Issue by rukaiya-rk-24** [SYSTRAN/faster-whisper#644]
There was this issue with whisper that even after loading on cuda, it did not load properly on cuda, hence how can I check if my model is loaded on gpu only and if it utilizes gpu?

**Comment by gongouveia** [comment]
If on linux, use nvtop or nvidia-smi, verify if in the inference time there is GPU usage.

In Windows you can do the same, using the task manager for example.

**Comment by rukaiya-rk-24** [comment]
Using nvidia-smi does return Tesla T4 I just want to check if my model is correctly loaded on gpu?

**Comment by gongouveia** [comment]
Using nvtop you can see if there was any gpu memory usage, when you run inference on it. [https://github.com/Syllo/nvtop](ref)

**Comment by rukaiya-rk-24** [comment]
Okay, thanks a lot for your help!
