### ISSUE TITLE
CUDA failed with error forward compatibility was attempted on non supported HW

### ISSUE THREAD

**Issue by opencvbaby** [SYSTRAN/faster-whisper#653]
RuntimeError: CUDA failed with error forward compatibility was attempted on non supported HW

NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 12.1  
2080ti

**Comment by trungkienbkhn** [comment]
Hello. Could you reboot or reset nvidia drivers then run again ?
https://stackoverflow.com/a/45319156/1391392
