### ISSUE TITLE
Is it possible to transcribe audio segments with chunk_length longer that 30?

### ISSUE THREAD

**Issue by vmouchakis** [SYSTRAN/faster-whisper#676]
When transcribing audio segments with a chunk_length longer than 30 using the Faster-whisper model, only the first 30 seconds of audio are transcribed, and the rest of the audio is ignored. This behavior is not consistent with the behavior of the vanilla Whisper model, which successfully transcribes the entire audio segment.

Example:
Given an input with chunk_length=66, the vanilla Whisper model, successfully transcribes the whole audio, while the Faster-whisper only transcribes the first 30.

Is it possible to do this? If not, is there any way around this?

**Comment by swiftraccoon** [comment]
https://github.com/SYSTRAN/faster-whisper/blob/f144e4c83d54f3c3304b6a75a3f563e5f84de6cf/faster_whisper/transcribe.py#L218

Have you tried setting it?

**Comment by vmouchakis** [comment]
Hi.

I am getting a KeyError. I also tried to change it here <https://huggingface.co/Systran/faster-whisper-large-v3/blob/edaa852ec7e145841d8ffdb056a99866b5f0a478/preprocessor_config.json#L2> and I got an error regarding dimensions. Trying any value larger than 30 was giving me this error. Values less than 30 were working fine.

Best regards,
Vasilis
