### ISSUE TITLE
segment /chunk is too long

### ISSUE THREAD

**Issue by sd816224** [SYSTRAN/faster-whisper#681]
hi there,
each segment of srt  output is a bit too long for me,
then i turn on vad_filter and adjust the max_speech_duration_s to 2.
it still output segment much more than 2 seconds.

not sure if the function (get_speech_timestamps) of VadOptions works properly here to split the long speech chunk?
thanks a lot

**Comment by Purfview** [comment]
>  i turn on vad_filter

VAD filter has nothing to do with text length.

> segment of srt output

This repo doesn't have srt writer, you should ask at the repo which srt writer you are using.

You can try Standalone Faster-Whisper from there -> https://github.com/Purfview/whisper-standalone-win
Try `--standard` or `--standard_asia`, or other settings for srt/vtt output.
