### ISSUE TITLE
Update PyPi package

### ISSUE THREAD

**Issue by Blucknote** [SYSTRAN/faster-whisper#682]
There a few changes in repo which still not present in package.
At least new argument was added to transcribe method 3 weeks ago https://github.com/SYSTRAN/faster-whisper/commit/ad3c83045bc0748b744e064ddfda680c86662e7e#diff-e027202a963607f9c883ac3365c78f2939f3e41bd8fb9b119ac718e0d3e2314c
and last release was [27 November 2023](https://pypi.org/project/faster-whisper/#history)

**Comment by Purfview** [comment]
The bleeding edge builds doesn't go to PyPi packages, there it goes by the stable versions.
