### ISSUE TITLE
Transcription is working badly without internet connection

### ISSUE THREAD

**Issue by Da6hkin** [SYSTRAN/faster-whisper#686]
I've used the project to transcript some text without the internet. I don't even get full text from my speech. It returns either first part or last part or strange text from the speech. Can I do something with this? I am using local medium model

**Comment by gongouveia** [comment]
Internet connection should not affect the reuslt. Models and inference are done in local computer.

What are yout translation configuration options?
Seem sto be VAD options, or audio problem

**Comment by Da6hkin** [comment]
VAD filter turned off, settings regarding translation configuration as I udnerstand are showed in the image

> Internet connection should not affect the reuslt. Models and inference are done in local computer.
> 
> What are yout translation configuration options? Seem sto be VAD options, or audio problem

![photo_2024-02-14_14-45-44](https://github.com/SYSTRAN/faster-whisper/assets/49761308/32ca8e8b-3e54-4172-9c8a-ee9f34215f0f)

**Comment by gongouveia** [comment]
Have you tried savinf the captured audio and listening to it? is it ok?
