### ISSUE TITLE
distil + word_timestamps=True => CRASH

### ISSUE THREAD

**Issue by ExtReMLapin** [SYSTRAN/faster-whisper#688]
Hello,
When using [this finetuned version of distil whisper](https://huggingface.co/bofenghuang/whisper-large-v3-french-distil-dec16) and trying to use `word_timestamps=True` it crashes when starting the transcription, no issue when `word_timestamps=False`

It's a CRASH, not a python error, it straight exits the python instance, no crash message, nothing, just byebye amigo hasta la vista

**Comment by Purfview** [comment]
Is that model working with vanilla Whisper and word_timestamps=True?

**Comment by ExtReMLapin** [comment]
yes

gave a try with

```python
import whisper
# Load model
model = whisper.load_model("./models/whisper-large-v3-french-distil-dec16/original_model.pt")

# Transcribe
result = model.transcribe("./tmp0p6z2kmk_short.wav", language="fr", word_timestamps=True)
print(result)
```

**Comment by trungkienbkhn** [comment]
@ExtReMLapin , hello. I encoutered similar error with you when running with `word_timestamps=True`. You can see this [comment](https://github.com/SYSTRAN/faster-whisper/pull/557#issuecomment-1851470485).
My error came from the alignment_heads field in the model's config.json file. Can you re-check this file in your finetuned model ?
For exact error, you can check this [comment](https://github.com/SYSTRAN/faster-whisper/pull/557#issuecomment-1878097665).
Besides, you should add `condition_on_previous_text=False` to improve the transcription quality.
Hope it's helpful to you.

**Comment by bofenghuang** [comment]
Hi @ExtReMLapin ,

Just fixed the issue [here](https://huggingface.co/bofenghuang/whisper-large-v3-french-distil-dec2/discussions/1), thanks to @Jeronymous!

By the way, for this version, it's true that `condition_on_previous_text=False` will yield better performance for long-form sequential decoding, as pointed out by @trungkienbkhn.
