### ISSUE TITLE
cpu and gpu recognite result differently，gpu recognition all the way '!' and long video cuda out of memory

### ISSUE THREAD

**Issue by xuanyinmu** [SYSTRAN/faster-whisper#689]
model: large-v3
**question**: 
1. when I use cpu to transctibe, it can recognite the speech correctly, but when I use gpu to transcribe, it output all '!', and it detected language 'en' with probability nan
detected language:
![language](https://github.com/SYSTRAN/faster-whisper/assets/60185303/7cc8f71b-450b-4b0e-9054-22cec0be7c3d)

2. and when I use gpu, it loaded the model into gpu memory, but when I look at the gpu usage in task manager I see that it is 0% from time to time, is this correct?
the gpu usage:
![gpu using](https://github.com/SYSTRAN/faster-whisper/assets/60185303/512f4d05-222e-437e-9bf8-69babf46bc43)

**recognite result**:
cpu:
![cpu result](https://github.com/SYSTRAN/faster-whisper/assets/60185303/241a0f75-0e47-445b-b9ef-f4b2feb3af64)
gpu:
![gpu result](https://github.com/SYSTRAN/faster-whisper/assets/60185303/30dc6b95-1382-48d5-ba57-98c451ac20e5)

this is my code:
gpu version:
```python
from faster_whisper import WhisperModel
from changevideospeed import SearchVideoFiles
import pysubs2

def GetSubtitleResult(results : list, audio_path: str) -> tuple:
    subs: pysubs2.SSAFile = pysubs2.load_from_whisper(results)
    file_name = audio_path[:audio_path.rfind('.')]
    
    return (subs, file_name)

def SaveSRT(results : list, audio_path: str) -> None:
    subs, file_name = GetSubtitleResult(results, audio_path)
    subs.save(file_name+'.srt')

def SaveASS(results : list, audio_path: str) -> None:
    subs, file_name = GetSubtitleResult(results, audio_path)
    subs.save(file_name+'.ass')

def LoadModel(model_size: str, download_root: str = 'models/') -> WhisperModel:
    model: WhisperModel = WhisperModel(download_root = download_root, model_size_or_path = model_size,
                            device='cuda', # cpu_threads=12,
                            compute_type='float16',
                            local_files_only = True)
    return model

def Transcribe(model : WhisperModel, audio_path: str, language:str = None) -> list:
    segments, info = model.transcribe(audio = audio_path, language = language)
    segments = list(segments)

    print("Detected language '%s' with probability %f" % (info.language, info.language_probability))
    
    results= []
    for s in segments:
        segment_dict = {'start':s.start,'end':s.end,'text':s.text}
        results.append(segment_dict)
    
    return results

if __name__ == '__main__':
    audio_dir = 'audio'
    file_paths = SearchVideoFiles(audio_dir)
    model_size = 'large-v3'

    model: WhisperModel = LoadModel(model_size)
    for path in file_paths:
        results: list = Transcribe(model, path)
        SaveSRT(results, path)
```
cpu version: just change the LoadModel function
```python
def LoadModel(model_size: str, download_root: str = 'models/') -> WhisperModel:
    model: WhisperModel = WhisperModel(download_root = download_root, model_size_or_path = model_size,
                            device='cpu', cpu_threads=12,
                            # compute_type='float16',
                            local_files_only = True)
    return model
```
if anyone can help me, thank you very much!

**Comment by Purfview** [comment]
> cpu and gpu recognite differently

Because different compute type is used, use same ->`int8_float32`.

> gpu recognite is all '!'

`large-v3` model tends to hallucinate a lot, try `large-v2`.
Or try [this PR](https://github.com/SYSTRAN/faster-whisper/commit/00efce1696c21310bbdfd58433adfc8d44c2edbc) [it's not on pipy yet], with it a model should recover from such hallucination loop.

**Comment by xuanyinmu** [comment]
> > cpu and gpu recognite differently
> 
> Because different compute type is used, use same ->`int8_float32`.
> 
> > gpu recognite is all '!'
> 
> `large-v3` model tends to hallucinate a lot, try `large-v2`. Or try [this PR](https://github.com/SYSTRAN/faster-whisper/commit/00efce1696c21310bbdfd58433adfc8d44c2edbc) [it's not on pypi yet], with it a model should recover from such hallucination loop.

I change the compute type to 'int8_float32', it worked and really fast
And I try your gived PR, it seem to no different to no change the code

I will use int8_float32 to run the code, in addition, thank you very much!

**Comment by Purfview** [comment]
> And I try your gived PR, it seem to no different to no change the code

Did you tried with `float16`?

**Comment by xuanyinmu** [comment]
> > And I try your gived PR, it seem to no different to no change the code
> 
> Did you tried with `float16`?

yes, I accord to the PR code and use 'float16'

**Comment by xuanyinmu** [comment]
> > And I try your gived PR, it seem to no different to no change the code
> 
> Did you tried with `float16`?

hi guy, I have a new question. cuda ouput error: cuda out of memory of very video file. 
I try to transcribe some long video(maximum 11 hours, at least 1 hour), the video language is chinese and mix little english.
If I extract audio from the video, can I fix it? And then if can not fix it, how can I do? Using the medium or smaller model? But if use smaller model, I worry about the accuracy.

**Comment by Purfview** [comment]
> I accord to the PR code and use 'float16'

What debug shows?
```python
import logging
logging.basicConfig()
logging.getLogger("faster_whisper").setLevel(logging.DEBUG)
```

> cuda out of memory

Try `best_of=1`

**Comment by xuanyinmu** [comment]
> > I accord to the PR code and use 'float16'
> 
> What debug shows?
> 
> ```python
> import logging
> logging.basicConfig()
> logging.getLogger("faster_whisper").setLevel(logging.DEBUG)
> ```
> 
> > cuda out of memory
> 
> Try `best_of=1`

1. I change the code follow PR again and reuse the `float16`, it still output '!' all the way.
this is the loging: （It's so time-consuming to start a log.）
```
INFO:faster_whisper:Processing audio with duration 00:45.909
INFO:faster_whisper:VAD filter removed 00:03.349 of audio
DEBUG:faster_whisper:VAD filter kept the following audio segments: [00:02.928 -> 00:09.600], [00:09.600 -> 00:16.464], [00:16.560 -> 00:24.512], [00:24.512 -> 00:29.072], [00:29.104 -> 00:32.976], [00:33.072 -> 00:45.712]
INFO:faster_whisper:Detected language 'en' with probability nan
DEBUG:faster_whisper:Processing segment at 00:00.000
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.0 (18.666667 > 2.400000)
DEBUG:faster_whisper:Log probability threshold is not met with temperature 0.0 (-291.128876 < -1.000000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.2 (18.666667 > 2.400000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.4 (18.666667 > 2.400000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.6 (18.666667 > 2.400000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.8 (18.666667 > 2.400000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 1.0 (18.666667 > 2.400000)
DEBUG:faster_whisper:Processing segment at 00:30.000
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.0 (18.500000 > 2.400000)
DEBUG:faster_whisper:Log probability threshold is not met with temperature 0.0 (-293.739897 < -1.000000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.2 (18.500000 > 2.400000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.4 (18.500000 > 2.400000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.6 (18.500000 > 2.400000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 0.8 (18.500000 > 2.400000)
DEBUG:faster_whisper:Compression ratio threshold is not met with temperature 1.0 (18.500000 > 2.400000)
Detected language 'en' with probability nan
```
2. when I change the `best_of = 1`，it feels like the transcription is much slower than the default `best_of = 5`, can I add the number of the `best_of`?

**Comment by Purfview** [comment]
Ah, I forgot that there is one more PR to fix hallucination loops [and not in v0.10.0] - https://github.com/SYSTRAN/faster-whisper/commit/ebcfd6b9646f5176fba8b7f3429d0de28a70192c

> best_of = 1，it feels like the transcription is much slower than the default best_of = 5

It should be faster.

**Comment by xuanyinmu** [comment]
> Ah, I forgot that there is one more PR to fix hallucination loops [and not in v0.10.0] - [ebcfd6b](https://github.com/SYSTRAN/faster-whisper/commit/ebcfd6b9646f5176fba8b7f3429d0de28a70192c)
> 
> > best_of = 1，it feels like the transcription is much slower than the default best_of = 5
> 
> It should be faster and take less VRAM. Transcription accuracy can be a bit less accurate.

It's been almost two hours, the first 8 hours of video has not been transcribed yet, and a couple of exceptions should have been thrown when setting `best_of=5` earlier (laughs)
my faster-whisper version is 0.10.0, but in the local transcribe.py not have the you give new link's code, do I still need to change the code?

**Comment by Purfview** [comment]
Sorry, I can't understand you.

**Comment by xuanyinmu** [comment]
> Sorry, I can't understand you.

my english is poor, sorry 
where you can't understand?

**Comment by Purfview** [comment]
> Where are you unable to understand?

All of the post.

**Comment by xuanyinmu** [comment]
> Ah, I forgot that there is one more PR to fix hallucination loops [and not in v0.10.0] - [ebcfd6b](https://github.com/SYSTRAN/faster-whisper/commit/ebcfd6b9646f5176fba8b7f3429d0de28a70192c)
> 
> > best_of = 1，it feels like the transcription is much slower than the default best_of = 5
> 
> It should be faster and take less VRAM. Transcription accuracy can be a bit less accurate.

I try `flaot16` again.I've modified transcribe.py with the code from the two PR links you gave, but it still keeps outputting '!', and it transcribe much slower than use `int8_float32`
**transcribe.py**:
![transcribepy_code](https://github.com/SYSTRAN/faster-whisper/assets/60185303/3afa379e-3dee-4bb9-90b2-e84a43943e79)

 **transcribe result**:
![result](https://github.com/SYSTRAN/faster-whisper/assets/60185303/d79fda5b-e2ce-43d5-9bb2-eeb02f87f1c7)

**transcription time**:
![time](https://github.com/SYSTRAN/faster-whisper/assets/60185303/cdb71d3b-2caa-4823-b440-e16dc1222c11)

**Comment by xuanyinmu** [comment]
> > Where are you unable to understand?
> 
> All of the post.

1. when I change `best_of` to equal 1, it can transcribes properly and reports no errors, but I feel it slower than `best_of=5`(but you say it should be faster, so we skip the question)
2. you say `best_of=1` will reduced transcription accuracy. so should I increase the value of `best_of`? if so how much should I change the value? my GPU is 1660ti (6G) , I worry about I'll still get the 'cuda out of memory' error!

**Comment by Purfview** [comment]
>  it still keeps outputting '!'

What version of cuDNN you are using? Some old versions have weird bugs.

> best_of=1 will reduced transcription accuracy. So, should I increase the value of best_of appropriately?

Yes, try to increase it incrementally till you don't get "out of memory" error.

**Comment by xuanyinmu** [comment]
> > it still keeps outputting '!'
> 
> What version of cuDNN you are using? Some old versions have weird bugs.
> 
> > best_of=1 will reduced transcription accuracy. So, should I increase the value of best_of appropriately?
> 
> Yes, try to increase it incrementally till you don't get "out of memory" error.

cuda version: 11.4 in path but 11.3 in python output
cudnn version: 8.2.2 in cudnn_version.h but it show 8302 in python output
cuda path:
![path](https://github.com/SYSTRAN/faster-whisper/assets/60185303/3205e769-deb4-4dfb-a56e-fb16d5737ace)
cudnn_version.h:
![flie](https://github.com/SYSTRAN/faster-whisper/assets/60185303/03a8c03b-af22-4abd-8698-9664528e0117)
output:
![output](https://github.com/SYSTRAN/faster-whisper/assets/60185303/3ab5d1f0-26c7-403d-8c85-3ed19dcec90b)

**Comment by Purfview** [comment]
> cudnn version: 8.2.2 

That's very old, maybe it's buggy and slow. Try to update it.

**Comment by xuanyinmu** [comment]
> > cudnn version: 8.2.2
> 
> That's very old, maybe it's buggy and slow. Try to update it.

ok, I will try it after, thanks for your help!
