### ISSUE TITLE
No module named 'faster_whisper'

### ISSUE THREAD

**Issue by nirual81** [SYSTRAN/faster-whisper#691]
I have tried to switch from openai_whisper to faster_whisper. For that I have created a new venv and run the pip installation.
But for some reason, the library is not there. And it throws the ModuleNotFoundError.
After several reinstalls and --force-reinstall, I gave up. (For testing I am running the first Example from the README)

**Comment by Purfview** [comment]
Try `faster-whisper`.

**Comment by nirual81** [comment]
@Purfview This is how I am Importing the Library:
from faster_whisper import WhisperModel

And this is the Error that it throws:
    from faster_whisper import WhisperModel
ModuleNotFoundError: No module named 'faster_whisper'

For Installation I have used:
pip install faster-whisper

And later:
pip install --force-reinstall "faster-whisper @ https://github.com/guillaumekln/faster-whisper/archive/refs/heads/master.tar.gz"

But every time, it says that it is already Installed. And after removing the whole library from the venv and installing it again, nothing has changed and it throws still that error.

**Comment by Purfview** [comment]
>from faster_whisper import WhisperModel

`from faster_whisper.transcribe import WhisperModel`

**Comment by Purfview** [comment]
Maybe something with venv, read there: https://stackoverflow.com/questions/72821332/importing-modules-from-a-virtual-environment-in-python

**Comment by nirual81** [comment]
@Purfview The Environment gets initialized and other libraries are working like it should. I first thought that I messed up something with the venv, but if I tried to run my project with the fast_whisper stuff commented out, it runs just fine.

**Comment by WeberJulian** [comment]
I got the same issue, it turned out I had a python file called `faster_whisper.py` at the root of the project so the module got overridden. Check for that.
