### ISSUE TITLE
CMD usage

### ISSUE THREAD

**Issue by FurkanGozukara** [SYSTRAN/faster-whisper#693]
I use whisper as below and working great

is that possible for faster whisper too?

`whisper "C:\temp\a\1.mp3" --model large-v1 --language en --initial_prompt "Welcome our Youtube channel." --best_of 10 --beam_size 10 --word_timestamps True --highlight_words True --max_words_per_line 8 --output_dir  "C:\temp\a"`

**Comment by Purfview** [comment]
This repo doesn't have CLI, for CLI functionality look at these repos:
https://github.com/Softcatala/whisper-ctranslate2
https://github.com/Purfview/whisper-standalone-win

**Comment by FurkanGozukara** [comment]
> This repo doesn't have CLI, for CLI functionality look at these repos: https://github.com/Softcatala/whisper-ctranslate2 https://github.com/Purfview/whisper-standalone-win

thanks a lot testing whisper-ctranslate2

**Comment by FurkanGozukara** [comment]
> This repo doesn't have CLI, for CLI functionality look at these repos: https://github.com/Softcatala/whisper-ctranslate2 https://github.com/Purfview/whisper-standalone-win

it doesnt support

word_timestamps
highlight_words
and
max_words_per_line
?

**Comment by Purfview** [comment]
>word_timestamps

Supported.

>highlight_words

Supported.

>max_words_per_line

Not supported.

**Comment by FurkanGozukara** [comment]
> whisper-ctranslate2

I tried whisper-ctranslate2

thanks for further info
