### ISSUE TITLE
How to implement microphone transcription using Faster Whisper?

### ISSUE THREAD

**Issue by 20246688** [SYSTRAN/faster-whisper#700]

**Comment by ramzeez88** [comment]
here , you can try this:
import pyaudio
import wave
from faster_whisper import WhisperModel
import os

os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'
CHUNK = 1024
FORMAT = pyaudio.paInt16
CHANNELS = 2
RATE = 44100
RECORD_SECONDS = 5
WAVE_OUTPUT_FILENAME = "output.wav"

model_size = "distil-large-v3"
model = WhisperModel(model_size, device="cuda", compute_type="int8_float16")

p = pyaudio.PyAudio()

stream = p.open(format=FORMAT,
                channels=CHANNELS,
                rate=RATE,
                input=True,
                frames_per_buffer=CHUNK)

print("* recording")

while True:
    frames = []

    for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
        data = stream.read(CHUNK)
        frames.append(data)

    wf = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
    wf.setnchannels(CHANNELS)
    wf.setsampwidth(p.get_sample_size(FORMAT))
    wf.setframerate(RATE)
    wf.writeframes(b''.join(frames))
    wf.close()

    segments, info = model.transcribe(WAVE_OUTPUT_FILENAME, beam_size=5, language="en", condition_on_previous_text=False)

    for segment in segments:
        print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))

**Comment by 20246688** [comment]
请问没有使用vad模型吗？

**Comment by 20246688** [comment]
> 在这里，你可以试试这个： import pyaudio import wave from faster_whisper import WhisperModel import os
> 
> os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE' CHUNK = 1024 格式 = pyaudio.paInt16 通道 = 2 速率 = 44100 RECORD_SECONDS = 5 WAVE_OUTPUT_FILENAME = “output.wav”
> 
> model_size = “distil-large-v3” model = WhisperModel（model_size， device=“cuda”， compute_type=“int8_float16”）
> 
> p = pyaudio 的 PyAudio。PyAudio（）
> 
> stream = p.open（格式=格式，通道=CHANNELS，速率=RATE，输入=True，frames_per_buffer=CHUNK）
> 
> print（“* 录制”）
> 
> while True 时：frames = []
> 
> ```
> for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
>     data = stream.read(CHUNK)
>     frames.append(data)
> 
> wf = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
> wf.setnchannels(CHANNELS)
> wf.setsampwidth(p.get_sample_size(FORMAT))
> wf.setframerate(RATE)
> wf.writeframes(b''.join(frames))
> wf.close()
> 
> segments, info = model.transcribe(WAVE_OUTPUT_FILENAME, beam_size=5, language="en", condition_on_previous_text=False)
> 
> for segment in segments:
>     print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
> ```

请问没有使用vad模型吗？
