### ISSUE TITLE
Large-v3 model Issues

### ISSUE THREAD

**Issue by wjc1989** [SYSTRAN/faster-whisper#701]
I update new model Large-v3, we meet these problems:
command : whisper-ctranslate2 1.wav --model large-v3

1) Occasionally, advertising slogans may appear, and at the beginning or end of the voice, there may be advertisements that are forgotten by the mirror. Please subscribe to some advertisements;

2) Sometimes a speech is translated into a paragraph without dividing it into time intervals. The voice I tested was a conversation between two texts, but the result did not show a question and answer effect.

Please provide suggestions, thank you very much

**Comment by OneAtDrt** [comment]
this was discussed here https://github.com/openai/whisper/discussions/928#discussioncomment-5372187
