### ISSUE TITLE
slower inference with 1.0.0 compared to 0.10.0

### ISSUE THREAD

**Issue by thomasmol** [SYSTRAN/faster-whisper#703]
I am getting about 4x slower inference with version 1.0.0 compared to 0.10.0.

I used a 1 min 17 sec sample file, run on an A10G GPU

Before:
`Finished transcribing, took 5.043 seconds. Detected language: en`

Now:
`Finished transcribing, took 21.936 seconds. Detected language: en`

I did not change my config other than upgrading to 1.0.0

Only seems to happen on very short files, tested a 25 min file that transcribed at the same speed as before.

Any ideas?

**Comment by trungkienbkhn** [comment]
@thomasmol , hello. Can you check this [PR](https://github.com/SYSTRAN/faster-whisper/pull/705) and rerun your tests ?

**Comment by thomasmol** [comment]
That fixes it! `Finished transcribing, took 5.1937 seconds. Detected language: en` back to normal
