### ISSUE TITLE
PyPI 0.10.0 

### ISSUE THREAD

**Issue by Moumeneb1** [SYSTRAN/faster-whisper#704]
It seems like faster_whisper==0.10.0 is pointing to the wrong package build, it's not pointing to the v0.10.0 that has the ctranslate2 <4.0 requirements but to another code.

**Comment by thomasmol** [comment]
yea there was a bug with version numbers. i think you can point to 0.10.1 to get 0.10.0 (only difference is version number)

**Comment by jordimas** [comment]
See also: https://github.com/SYSTRAN/faster-whisper/issues/699

If you want to use the old 0.10.0, you need to use now 0.10.1 since the old 0.10 was overwriten by mistake
