### ISSUE TITLE
1.0 fix yet for faster-whisper?

### ISSUE THREAD

**Issue by BBC-Esq** [SYSTRAN/faster-whisper#711]
Is anyone else besides myself impressed by @Purfview and how quick he troubleshot some issues with faster-whisper and openai's code?  Just throwing that out there.  Any permanent fixes on the horizon yet?  I'm using 0.9.0 right now in my transcriber program because of the recent shuffle...

**Comment by Purfview** [comment]
What fix? 1.0 should be working OK.
If you want CUDA 11 or 0.10.0 then you need to install `0.10.1`.

**Comment by kurianbenoy** [comment]
Yeah with the new version. This stable package became a mess.

It affected work at company and personal projects 😀. I am not bashing the hard working contributors of this project, yet just saying.

**Comment by BBC-Esq** [comment]
I changed my dependencies to use faster-whisper 0.9.0 and it solved the issues for users of my transcriber program.  If there's been resolute fixes in the last day then perhaps I can shift to 1.0 now?  For example here:

https://github.com/BBC-Esq/ctranslate2-faster-whisper-transcriber/issues/3

**Comment by kurianbenoy** [comment]
Thank you for sharing what you did @BBC-Esq

**Comment by doublex** [comment]
Yup, +1
I have applied any pull-request from @Purfview - before it got merged...

**Comment by BBC-Esq** [comment]
I tested v0.10.1 by downloading cudnn and cublas libraries straight from the nvidia website.  I used cuDNN 8.9.7 for cuda 11 per here:

![image](https://github.com/SYSTRAN/faster-whisper/assets/108230321/ac62002b-ee6f-4f8f-b796-8edbb83de28a)

I used cublas per here:

![image](https://github.com/SYSTRAN/faster-whisper/assets/108230321/d6ac12aa-2774-4faa-92e7-f62871d150c0)

I tested it with my repository here and it seemed to work properly:

https://github.com/BBC-Esq/ctranslate2-faster-whisper-transcriber

How is it possible that it worked properly even though I had cuda 12 installed?  This would help me understand faster-whisper...Does faster-whisper 0.10.1 rely on the CUDA toolkit 11.8 to be installed, for example, or is it more accurate to say that it simply relies on the cublas and cudnn ```.dll``` files that are associated with cuda toolkit 11.8?

I associated "support for CUDA 12" as requiring installing the CUDA 12+ toolkit...but if it's just the specific .dll files that are needed, I could advise users to just make sure and use the correct .dll files and that it doesn't matter which version of the cuda toolkit is "installed."   Thanks!

**Comment by thomasmol** [comment]
@BBC-Esq What exact issues are you having? Does it really matter if it's working? As stated before, `0.10.1` is exactly the same as `0.10.0` apart from a version change. The version number changed because of a bug with releasing `1.0.0`, so if you want to use the original version of `0.10.0` just use `0.10.1`. There is still a latency issue with 1.0, but a PR is already made for a fix.

**Comment by BBC-Esq** [comment]
> @BBC-Esq What exact issues are you having? Does it really matter if it's working? As stated before, `0.10.1` is exactly the same as `0.10.0` apart from a version change. The version number changed because of a bug with releasing `1.0.0`, so if you want to use the original version of `0.10.0` just use `0.10.1`. There is still a latency issue with 1.0, but a PR is already made for a fix: #705

@thomasmol It matters to me because I like to understand things and it'll help me understand things further down the road.  Just curious if anyone knows whether "CUDA toolkit" is required or if faster-whisper, technically, only needs the relevant .dll files.  The faster-whisper installation instructions don't say anything about installing the CUDA toolkit.

Thanks for the recap about where version 1.0 is at.  There's been a fair amount of discussion the last few days.

**Comment by kurianbenoy** [comment]
@BBC-Esq what might be a good docker image  for working in this version?

In your case did you test CUDNN version of 11.8?

**Comment by BBC-Esq** [comment]
> @BBC-Esq what might be a good docker image for working in this version?
> 
I don't understand if you're asking a question or making a recommendation here...

> In your case did you test CUDNN version of 11.8?

Regarding my test, I have CUDA 12.3 installed but I downloaded the cudnn .dll file for cuda 11; specifically cuDNN 8.9.7.  You have to create an nvidia developer account, which is free, and here's the name of the zip archive:

![image](https://github.com/SYSTRAN/faster-whisper/assets/108230321/022c0265-8645-4bdc-b87a-96ab9b9bdc9d)

**Comment by thomasmol** [comment]
> If nobody knows the definitive answer I'll eventually just uninstall the CUDA toolkit, place the .dll files in my directory, and test myself...

Why don't you test it yourself anyway? Seems faster than waiting for others to test and find out?

**Comment by BBC-Esq** [comment]
> > If nobody knows the definitive answer I'll eventually just uninstall the CUDA toolkit, place the .dll files in my directory, and test myself...
> 
> Why don't you test it yourself anyway? Seems faster than waiting for others to test and find out?

I will, but thought someone might know the answer off the top of their head.  But yes, at this point I've spent more time talking about it than it would have taken to test.  If this community is either people don't know, or just don't want to help, that's fine and I'm capable of teaching myself I supppose.  Thanks.
