### ISSUE TITLE
new version support cuda12 Older versions affected

### ISSUE THREAD

**Issue by jax-explorer** [SYSTRAN/faster-whisper#714]
the faster-whisper 1.0.0 version support cuda12
<img width="1215" alt="截屏2024-02-25 10 41 55" src="https://github.com/SYSTRAN/faster-whisper/assets/119055910/4ac08c4b-5e95-45c6-8210-ff95df2fbc9b">

but Older versions affected
I use faster-whisper  0.10.0 version 

Collecting ctranslate2<5,>=4.0 (from faster-whisper==0.10.0->-r /requirements.txt (line 2))
  Downloading ctranslate2-4.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)

**Comment by Purfview** [comment]
Read there https://github.com/SYSTRAN/faster-whisper/issues/699
