### ISSUE TITLE
More than twice but less than three times faster than openai/whisper，not 4 times

### ISSUE THREAD

**Issue by tuotuoshao** [SYSTRAN/faster-whisper#720]
device: A30
version: 0.10.1
model: large-v2

Firstly i test a 90s audio，faster-whisper costs 8s，openai/whisper costs 20s.
Than i set the beam_size=5 in openai/whisper and get 23s.
Secondly i test a almost 13min audio，faster-whisper costs 51s and it is near to the value in https://github.com/SYSTRAN/faster-whisper#large-v2-model-on-gpu, but openai/whisper costs 140s，so different with the figure. 
Than i set the beam_size=5 in openai/whisper and get 160s.

**Comment by Purfview** [comment]
> less than three times faster

Math says that's **more** than three times faster.

160 / 51 = 3.137254901960784

>not 4 times

You are testing the different software versions on the different hardware.
