### ISSUE TITLE
Float16 issue

### ISSUE THREAD

**Issue by AntoineChatry** [SYSTRAN/faster-whisper#727]
Error : [ctranslate2] [thread 28968] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.

installed: cuda 11.8, cudnn: 9.
Using conda virtual env.
Cuda is in system path(nvcc --version work).
Here's the code:
```python
def transcribe(audio):
    model = WhisperModel("small")
    segments, info = model.transcribe(audio)
    language = info[0]
    print("Transcription language", info[0])
    segments = list(segments)

    for segment in segments:
        print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
    return language, segments
``` 
### Fixed : GPU doesn't have Tensorcores

**Comment by Ghostbird** [comment]
I'm running into this error too, and I don't understand how it's "Fixed". Yes, my GPU doesn't have tensor cores, but I've never needed those to run models using CUDA. Is there a way to make it work without tensor cores, or is it fundamentally impossible?

**Comment by Purfview** [comment]
>I'm running into this error too, and I don't understand how it's "Fixed".

This is not error. It's a warning.

**Comment by Ghostbird** [comment]
It's a `ValueError` in Python. That's not a warning.

UPDATE: It's not an issue caused by faster-whisper itself. It's `ctranslate2`. I'll go have a look at their issues instead.

**Comment by Purfview** [comment]
Set it to whatever you need:

```python
segments, info = model.transcribe(audio, compute_type=float32)
```

Or `int8` instead of `float32` if your GPU supports it.

**Comment by Ghostbird** [comment]
I couldn't figure out how to prevent `ctranslate2` from throwing here, so I switched to the `int8` quantised model. It works well if started with a language. Without being told a language _turbo_ is pretty terrible. It keeps picking up Dutch as Icelandic, Swedish, Danish or German.
