### ISSUE TITLE
audio data directly into model.trancribe()

### ISSUE THREAD

**Issue by sriharshaguthikonda** [SYSTRAN/faster-whisper#728]
is there  a way to directly pass audio data into model.transcribe(). i have been saving a file and thn passing it on . 

any help is much appreciatd

**Comment by trungkienbkhn** [comment]
@sriharshaguthikonda , hello. You can use `librosa` or `sounddevice` python lib to receive audio data as numpy ndarray format then send them to whisper model. Ex:
```python
import sounddevice as sd
import numpy as np
from faster_whisper import WhisperModel

print("Recording started")
duration = 10
sample_rate = 16000
audio_data = sd.rec(int(sample_rate * duration), samplerate=sample_rate, channels=1, dtype=np.float32)
sd.wait()
audio_data = audio_data.squeeze()
print("Recording stopped")

model = WhisperModel('large-v3', device='cuda')
segments, info = model.transcribe(audio_data, word_timestamps=True)
for segment in segments:
    print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
```
Hope that it's helpful for you.

**Comment by sriharshaguthikonda** [comment]
Thank you very much, and I dont think i understood everything but chatgpt was able too..! And this was created by a voice keyboard based on this code.!
