### ISSUE TITLE
Installation issue with faster-whisper 0.10.0: Dependency Conflict with ctranslate2 Version

### ISSUE THREAD

**Issue by dineshkumar20** [SYSTRAN/faster-whisper#735]
I'm trying to install version 0.10.0 of faster-whisper, which relies on the ctranslate2>=3.22,<4 package. However, when I execute pip3 install faster-whisper==0.10.0, it attempts to install version 4.0.0 of ctranslate2 instead of version 3.22.0. Also, I encounter errors like this. Can someone please tell me why it's trying to install latest version?
```The conflict is caused by:
    The user requested ctranslate2==3.22.0
    faster-whisper 0.10.0 depends on ctranslate2<5 and >=4.0
```

https://github.com/SYSTRAN/faster-whisper/blob/e1a218fab1ab02d637b79565995bf1a9c4c83a09/requirements.txt#L2C1-L2C21

**Comment by Purfview** [comment]
`0.10.0` is broken on pypi.
`0.10.1` is unbroken 0.10.0.

**Comment by dineshkumar20** [comment]
Thank you @Purfview. It worked
