### ISSUE TITLE
API server compatible with OpenAI

### ISSUE THREAD

**Issue by rvsh2** [SYSTRAN/faster-whisper#741]
Hi,

Is there an api server compatible with openai response type for faster whisper? I'm looking in the opensource space but can't find anything appropiate like this for standard whisper: https://github.com/ggerganov/whisper.cpp/tree/master/examples/server

Please help.

BR
Krzysztof

**Comment by phineas-pta** [comment]
no u need to setup yourself

**Comment by heimoshuiyu** [comment]
have a look https://github.com/heimoshuiyu/whisper-fastapi
