### ISSUE TITLE
Random YouTube transcriptions being returned by `large-v3` model

### ISSUE THREAD

**Issue by SeaDude** [SYSTRAN/faster-whisper#742]
When I start a websocket with `large-v3` running on the back end, the model responds with a bunch of (seemingly) YouTube transcriptions...

It often seems to be a cooking chanel :)

Is this a known thing? How do I remedy?

![image](https://github.com/SYSTRAN/faster-whisper/assets/8636973/230dd9b8-b4df-4189-85dc-d2b0d3f36a9c)

**Comment by phineas-pta** [comment]
it's called hallucination, a known issue of whisper, see openai/whisper#928 for more examples

for now the solution is to enable VAD
