### ISSUE TITLE
How to get the vtt file like i do in whisper? 

### ISSUE THREAD

**Issue by Abdelrhman-Sayed70** [SYSTRAN/faster-whisper#743]
in whisper i can get the .vtt file which contains the timestamps using the following command
```py
!whisper "audio.m4a" --model base --language English
```
**How to do so using fast whisper?**

**Comment by Purfview** [comment]
Here it doesn't have CLI nor an output writer.

Use "forks" with CLI:
https://github.com/Softcatala/whisper-ctranslate2
https://github.com/Purfview/whisper-standalone-win
