### ISSUE TITLE
beam_size size not working if using converted model

### ISSUE THREAD

**Issue by ewwink** [SYSTRAN/faster-whisper#744]
I want to use [cahya/whisper-large-id](https://huggingface.co/cahya/whisper-large-id)

```
ct2-transformers-converter --model "cahya/whisper-large-id" \
--output_dir "cahya-whisper-large-id-ct2" --quantization float16
```

but changing `beam_size` has no effect, it always return 30 second segments, I want under 5 second

```
model = WhisperModel("cahya-whisper-large-id-ct2", device="cuda", compute_type="float16")
segments, _ = model.transcribe("voice.wav", beam_size=1, language="id") 
for segment in  list(segments):
    print("[%.2f -> %.2f] %s" % (segment.start, segment.end, segment.text))
```

**Comment by Purfview** [comment]
`beam_size` is not related to segments duration, it's size of [beam search](https://en.wikipedia.org/wiki/Beam_search).

**Comment by ewwink** [comment]
I don't know, but it work with model large-v3

default
![image](https://github.com/SYSTRAN/faster-whisper/assets/760764/feb925fd-6a75-49d9-801b-fa96a6dce515)


with beam_size=1
![image](https://github.com/SYSTRAN/faster-whisper/assets/760764/7eb444ec-9598-448b-8e4f-3122335b3423)

**Comment by Purfview** [comment]
On some other audio you can observe opposite effect.
