### ISSUE TITLE
Using GPU blocks for a few seconds after successful recognition

### ISSUE THREAD

**Issue by pedrofrau** [SYSTRAN/faster-whisper#745]
Hi,

I've been trying to implement faster-whisper on my project but I came across a weird issue. For some reason, when I use the GPU, Whisper successfully transcribes the audio very fast, but it still hooks the execution of the program for a few seconds. I've measured it. For instance using the distil-large model on the GPU takes 2s to do the transcription but up to 8s to free the execution of the program. This does not happen with the CPU which of course takes longer to transcribe, but frees the execution once the transcription is done.

The result being, the performance for CPU in time consumption is better on tiny and small models.

This is the code I used (directly copied from the README of this repo):
```
def recognize_whisper(audio_file, model_size="large-v3", processor='gpu'):
    # Run on GPU with FP16
    if processor == 'GPU':
        model = WhisperModel(model_size, device="cuda", compute_type="float16")

    # or run on GPU with INT8
    # model = WhisperModel(model_size, device="cuda", compute_type="int8_float16")
    # or run on CPU with INT8
    elif processor == 'CPU':
        model = WhisperModel(model_size, device="cpu", compute_type="int8")

    segments, info = model.transcribe(audio_file, beam_size=5, language='en')

    for segment in segments:
        print(segment.text)
```  
When executing this code with processor=='GPU', I'd see the transcription appear on screen quite fast, but the execution won't finish till a few seconds later.

And this is the output of the execution:
```
Testing for processor CPU
Testing Whisper model tiny...
Hi, my name is Peter and I'm testing Whisper with Becker.
Elapsed Time for Tiny: 1.22 seconds
Testing Whisper model small...
Hi, my name is Peter and I'm testing Whisper with Pepper.
Elapsed Time for Small: 4.96 seconds
Testing Whisper model medium...
Hi my name is Peter and I'm testing Whisper with Pepper
Elapsed Time for Medium: 12.27 seconds
Testing Whisper model large...
Hi, my name is Peter and I'm testing Whisper with Pepper.
Elapsed Time for Large: 25.58 seconds

Testing for processor GPU
Testing Whisper model tiny...
Hi, my name is Peter and I'm testing Wixford with Becker.
Elapsed Time for Tiny: 9.95 seconds
Testing Whisper model small...
Hi, my name is Peter and I'm testing Whisper with Pepper.
Elapsed Time for Small: 8.83 seconds
Testing Whisper model medium...
Hi my name is Peter and I'm testing Whisper with Pepper
Elapsed Time for Medium: 10.47 seconds
Testing Whisper model large...
Hi, my name is Peter and I'm testing Whisper with Pepper.
Elapsed Time for Large: 14.34 seconds
```

I'm currently running this on a Windows 11 machine, python 3.11 and Cuda 12/Cudnn 12 (I know the documentation suggested to use Cuda 11)

**Comment by trungkienbkhn** [comment]
@pedrofrau , hello. Please set the log level to debug and provide the full log. Besides, could you attach an audio file for testing?

**Comment by pedrofrau** [comment]
Sorry for taking so long, I did not see the comment.

Attached the full log and the audio file for testing.

I'm afraid the log does not give much information.

Log:
![image](https://github.com/SYSTRAN/faster-whisper/assets/19805221/cb2a4511-4343-4f65-88ef-23e9b32ba272)

Wav file:
[record.zip](https://github.com/SYSTRAN/faster-whisper/files/15236147/record.zip)

**Comment by trungkienbkhn** [comment]
@pedrofrau , from my testing in GPU,  I didn't see too much delay after the last sentence appears and the system exits completely.
FYI, with small model, the model loading time and the transcription time in CPU is faster than in GPU. So you can see that the total execution time of CPU is better than GPU.
In addition, for the GPU, it needs to be warmed up at the first run. The following executions will be faster than the first.

**Comment by pedrofrau** [comment]
Recalling my first post, this is the comparison between CPU and GPU among models.
```
Testing for processor CPU
Testing Whisper model tiny...
Hi, my name is Peter and I'm testing Whisper with Becker.
Elapsed Time for Tiny: 1.22 seconds

Testing for processor GPU
Testing Whisper model tiny...
Hi, my name is Peter and I'm testing Wixford with Becker.
Elapsed Time for Tiny: 9.95 seconds
```

I get that for tiny and small models CPU might be faster, but according to my observations, for a simple sentence such as "How are you" both CPU and GPU perform more or less the same in general terms, but GPU as I said takes longer to free the process after the recognition. Maybe I'm wrong, but since my issue is not with the time it takes to recognize but the time i takes to free the process after recognition, I wonder what is happening after the recognition that takes so long. To illustrate better my issue, let me attach a video. In my video you will see that audio is recognized with CPU very fast and test with GPU is launched immediately, but in the case of the GPU, you see how "Hi, pepper" appears on the screen also quite fast (so the recognition is indeed very fast), but the program takes longer to "finish".

[test_whisper.zip](https://github.com/SYSTRAN/faster-whisper/files/15272797/test_whisper.zip)

My guess is that there might be a background process blocking the execution and what I want to know is if that process can be somehow ignored or speeded up.

**Comment by trungkienbkhn** [comment]
I cann't reproduce your behavior. What GPU did you use ? I don't know if the GPU has any effect. Have you tried it on another machine ? I tested with T4 gpu on google colab and it still finished almost immediately.

**Comment by pedrofrau** [comment]
I tested it on two different machines (both laptops). One with an Nvidia RTX 4060 and the other with and Nvidia 5000 series. I don't know what else to tell you. If I figure out something else I'll keep you posted.

**Comment by pedrofrau** [comment]
If anyone is interested, I found out the problem is loading/unloading the model. So, if you use whisper on a separate function, and the model is loaded every time you call the function (hence unloaded once the function has finished), you will experience this "unexpected" latency after the recognition has finished. 
You can either load the module at first when launching you program and just leave it loaded until your program finishes, or as I did (due to my project's requirements), create a Flask server to run your whisper requests, then make requests directly to it and get the response on your main program (the latency will be there when launching the server and stopping the server, but not on every request)

Now, my server transcribes small audios in less than a second.
