### ISSUE TITLE
how to convert bytes to ndarray

### ISSUE THREAD

**Issue by acn-reginald-casela** [SYSTRAN/faster-whisper#749]
So, my code is taking in base64 audio data and converting it to bytes.

Is there a way to convert the bytes to ndarray and use that as data for faster-whisper?

As of the moment, I'm using 

np.frombuffer(audioBytes, np.int16).flatten().astype(np.float32) / 32768.0

but it's not producing the correct results when I use the ndarray.

**Comment by trungkienbkhn** [comment]
@acn-reginald-casela , hello. I think you don't need to convert bytes to ndarray since faster-whisper accepts audio as BinaryIO format. For example:
```python
with open(audio_path, "rb") as audio_file:
    audio_bytes = audio_file.read()
    audio_data = io.BytesIO(audio_bytes)
model = WhisperModel('large-v3', device='cuda')
segments, info = model.transcribe(audio_data, word_timestamps=True)
```

**Comment by acn-reginald-casela** [comment]
Tested this out and it worked. Thank you, @trungkienbkhn .
