### ISSUE TITLE
using VAD in `WhisperModel.transcribe()` causes onnxruntime to throw runtime exceptions on arm64

### ISSUE THREAD

**Issue by stubblyhead** [SYSTRAN/faster-whisper#751]
I'm running faster-whisper in AWS Lambda using container images, and have had good results thus far.  VAD filtering improved performance when running on an ec2 instance (t4g.medium), but throws the following errors when I try it in Lambda on arm64:
`terminate called after throwing an instance of 'onnxruntime::OnnxRuntimeException'`
`what():  /onnxruntime_src/include/onnxruntime/core/common/logging/logging.h:309 static const onnxruntime::logging::Logger& onnxruntime::logging::LoggingManager::DefaultLogger() Attempt to use DefaultLogger but none has been registered.`

Lambda on x86_64 however is able to use VAD filtering without error.

I'm using the AWS-maintained base image for Lambda with Python 3.12.1, faster-whisper 1.0.1, and onnxruntime 1.17.1.  Happy to provide any additional information if it would be helpful.

**Comment by phineas-pta** [comment]
u should raise issue in `onnxruntime` repo instead

**Comment by stubblyhead** [comment]
Why?  It's as likely to be a usage problem here as an implementation problem there.

**Comment by phineas-pta** [comment]
u can check source code to see how `onnxruntime` is used inside `fast er-whisper`

**Comment by stubblyhead** [comment]
just importing onnxruntime is enough to throw this error, so I think it's unlikely to be an issue in faster-whisper.  closing issue
