### ISSUE TITLE
Super long video processing failure

### ISSUE THREAD

**Issue by another1s** [SYSTRAN/faster-whisper#757]
I am tangled with a long video(about 5 hours) processing task and it kept running for about 24 hours and have not been finished yet, which takes much time than i expected and could possibly fail to generate ASR result. Is there a upper-limit video length for the model? i suspect it fell into infinite sequence generation problem.

**Comment by Purfview** [comment]
5 hours shouldn't be a problem for the modern hardware.
Try smaller model if you don't have GPU with CUDA.

**Comment by another1s** [comment]
> 5 hours shouldn't be a problem for the modern hardware. Try smaller model if you don't have GPU with CUDA.

i agree, but it just happend and i really have no idea why it is unexpectedly slow
it finally terminated with a bunch of hallucination outputs: some unrelevant sentences have been generated repeatedly...... i did utilize a Rtx4090 and lastest version of CUDA but it remains to be  unexpectedly slow. 
when inferencing, it took up 3688 MB GPU memory and 2640 seconds to process a video with 1200 seconds duration....

i am really confused

**Comment by Purfview** [comment]
Share your command.

**Comment by another1s** [comment]
[my_code.txt](https://github.com/SYSTRAN/faster-whisper/files/14751278/my_code.txt)
I only pasted the relevant function here.  

![server](https://github.com/SYSTRAN/faster-whisper/assets/21125331/d6a34156-6ccd-4d20-b441-b3b635c418f7)
![output_result1](https://github.com/SYSTRAN/faster-whisper/assets/21125331/2946f930-d7d3-464c-b9c5-2aa08286ba57)
the figure above are my gpu info screenshot and a glimpse of output result(too much to paste). the first line of the result is literally the same as the issue mention in https://github.com/openai/whisper/discussions/2015 ----- sentence from maybe training data or some else was generated.
i am wondering if the length of video correlates with the probability of model hallucination .

**Comment by another1s** [comment]
> [my_code.txt](https://github.com/SYSTRAN/faster-whisper/files/14751278/my_code.txt) I only pasted the relevant function here.
> 
> ![server](https://private-user-images.githubusercontent.com/21125331/316701391-d6a34156-6ccd-4d20-b441-b3b635c418f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MTk5ODYsIm5iZiI6MTcxMTQxOTY4NiwicGF0aCI6Ii8yMTEyNTMzMS8zMTY3MDEzOTEtZDZhMzQxNTYtNmNjZC00ZDIwLWI0NDEtYjNiNjM1YzQxOGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAyMjEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYjVhNzZlZjA0MzE3Mzk1NWMwYzc2YWU5ZTQ0NGNjZTgwZWYzMmVjMDIxMjBmZjY3OTJmNTkyMTAyMDNhMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4b6W7h3VGuIIQxZk0FGOVfX2y4pAqmsZ-b6F564ON1s) ![output_result1](https://private-user-images.githubusercontent.com/21125331/316701402-2946f930-d7d3-464c-b9c5-2aa08286ba57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MTk5ODYsIm5iZiI6MTcxMTQxOTY4NiwicGF0aCI6Ii8yMTEyNTMzMS8zMTY3MDE0MDItMjk0NmY5MzAtZDdkMy00NjRjLWI5YzUtMmFhMDgyODZiYTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAyMjEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZTkwYTk3NGNhODE2MTcyNjM2MjNhY2JjYmM0OTEzODMwOWRmZGQzMzY0Yzc1NzQ4N2JmOTc3ZmU3Yjg5ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mu_CNZBe1MJJqBsCM9YMhCg7rgYUWJvekol2fmcEGw4) the figure above are my gpu info screenshot and a glimpse of output result(too much to paste). the first line of the result is literally the same as the issue mention in [openai/whisper#2015](https://github.com/openai/whisper/discussions/2015) ----- sentence from maybe training data or some else was generated. i am wondering if the length of video correlates with the probability of model hallucination .

i guess my program ran so slow because of hallucination?

**Comment by Purfview** [comment]
> the first line of the result is literally the same as the issue mention in...

One line of hallucination is nothing to worry about.

> i guess my program ran so slow because of hallucination?

It's slow because you are running diarization there.

**Comment by another1s** [comment]
> > the first line of the result is literally the same as the issue mention in...
> 
> One line of hallucination is nothing to worry about.
> 
> > i guess my program ran so slow because of hallucination?
> 
> It's slow because you are running diarization there.

oh....i thought it was a tiny model and would not bother.  Thanks for your help, bug fixed
