### ISSUE TITLE
Word-level timestamp accuracy is lower than whisper-timestamped, is there any plan to optimize ?

### ISSUE THREAD

**Issue by pxEkin** [SYSTRAN/faster-whisper#759]

**Comment by Purfview** [comment]
Can you share a whisper-timestamped srt made of https://we.tl/t-0PS9iVQVv9

**Comment by pxEkin** [comment]
> Can you share a subtitle file produced with whisper-timestamped on https://we.tl/t-0PS9iVQVv9

Okay, here's one of my test results with whisper-timestamped https://we.tl/t-xO3dQFcVse
For faster-whisper, some other videos had inaccurate word timestamps, the timestamp has an early start and end condition

**Comment by Purfview** [comment]
I don't see higher accuracy, at the first glance I would say that your sample is less accurate than faster-whisper.

**Comment by pxEkin** [comment]
I run it with version 0.10.0, and script is:
`from faster_whisper import WhisperModel

model_size = "large-v2"

# Run on GPU with FP16
model = WhisperModel(model_size, device="cuda", compute_type="float16")

# or run on GPU with INT8
# model = WhisperModel(model_size, device="cuda", compute_type="int8_float16")
# or run on CPU with INT8
# model = WhisperModel(model_size, device="cpu", compute_type="int8")
segments, info = model.transcribe("./audio/Test_suntian.aac", vad_filter=True, vad_parameters=dict(min_silence_duration_ms=500), beam_size=5, word_timestamps=True)
print("Detected language '%s' with probability %f" % (info.language, info.language_probability))

for segment in segments:
    for word in segment.words:
        print("[%.2fs -> %.2fs] %s" % (word.start, word.end, word.word))`

@Purfview Is this related to the version and parameters? As far as I know, faster-whisper and whisper-timestamped handle word timestamps differently.
Here's another test result https://we.tl/t-8GEn6Rq2G3 【a little bug: highlight the same word in the same sentence only once】

**Comment by pxEkin** [comment]
the detect_disfluencies option of whisper_timestamped makes the word timestamp more accurate, can faster-whisper do this? because whisper-timestamped inference time is slow than faster-whisper, It would be great if faster-whisper could do it

**Comment by pxEkin** [comment]
> What means "this"?
I thought the whisper version and parameters you used locally were different from mine, which led to different results 【I think the faster-whisper timestamped are not so good】

> Btw, why your srt's are named as "whisperx"?
It's just that I didn't change the name of my whisperx test video, so don't worry about it


I found that faster-whisper mostly thinks that the start timestamp of the next word is the end timestamp of the last word,
![image](https://github.com/SYSTRAN/faster-whisper/assets/40013733/48f7de8b-17b2-42dd-8497-3cdf342ee078)
"from" duration time == pause time + actual duration time, there are quite a few such word-level timestamp problems

**Comment by Purfview** [comment]
In that red square:
the whisper-timestamped result is missing two timestamps, when faster-whisper result has one word too early, so, imo faster-whisper result is better.

Red arrow to "from":
It's not like that in your srt file. Anyway,  whisper-timestamped has missing that timestamp.

I think it's better that some timestamp is too early than don't have some timestamps at all.
