### ISSUE TITLE
I can't use language='zh' when I use large-v3

### ISSUE THREAD

**Issue by wntg** [SYSTRAN/faster-whisper#778]
warning: The current model is English-only but the language parameter is set to 'zh'; using 'en' instead.

**Comment by trungkienbkhn** [comment]
@wntg, hello. It seems you are using an English-only model like tiny.en, small.en, etc.
Could you try again with another multilingual model ?
Ex:
```python
from faster_whisper import WhisperModel

model = WhisperModel("large-v3", device="cuda")
segments, info = model.transcribe("audio.mp3", language="zh")
for segment in segments:
    print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
```

**Comment by wntg** [comment]
I used large-v3:
model_size = "large-v3"
model = WhisperModel(model_size, device="cuda", compute_type="float16")

**Comment by wntg** [comment]
> @wntg, hello. It seems you are using an English-only model like tiny.en, small.en, etc. Could you try again with other multilingual models ? Ex:
> 
> ```python
> from faster_whisper import WhisperModel
> 
> model = WhisperModel("large-v3", device="cuda")
> segments, info = model.transcribe("audio.mp3", language="zh")
> for segment in segments:
>     print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
> ```

I used large-v3:
model_size = "large-v3"
model = WhisperModel(model_size, device="cuda", compute_type="float16")

**Comment by trungkienbkhn** [comment]
It's a bit weird because "large-v3" is a multilingual model. This warning appears only with condition from [here](https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/transcribe.py#L401).
Could you show full code and attach your audio ?
