### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by BloumEM** [SYSTRAN/faster-whisper#782]
Hello ! I am going to ask a very noobish question, but how to run faster whisper after installation ?
I don't see any precision on the app to use the provided code.
Please can someone give me the initial process please ?

**Comment by Purfview** [comment]
> Hello ! I am going to ask a very noobish question, but how to run faster whisper after installation ? I don't see any precision on the app to use the provided code. Please can someone give me the initial process please ?

Example how to run it is on the main page -> https://github.com/SYSTRAN/faster-whisper#faster-whisper

If you are looking for "exe" then look there -> https://github.com/Purfview/whisper-standalone-win
