### ISSUE TITLE
change subtitles lenght per line

### ISSUE THREAD

**Issue by neozbr** [SYSTRAN/faster-whisper#800]
how to change subtitles lenght per line ? sometimes is putting 30 seconds of text into one subtitle how to fix this ?!

**Comment by trungkienbkhn** [comment]
FYI, FW does not support change subtitle length.
Sometimes model creates segments for 30s because it doesn't detect audio well and can't split the segments, maybe your audio has a lot of hallucination. You should use  VAD filter or a larger FW model to improve this.
