### ISSUE TITLE
How to use the local cached model?

### ISSUE THREAD

**Issue by LXRee** [SYSTRAN/faster-whisper#822]
hello, I have downloaded the model from huggingface and stored it in my local disk, but it seems it can not find my local stored model and try to download it online. The error is below
![微信截图_20240507170117](https://github.com/SYSTRAN/faster-whisper/assets/51704570/b4f30d88-31de-4daf-b3b9-d6083fa78bde)

**Comment by trungkienbkhn** [comment]
@LXRee , hello. You don't need to pass the local_files_only and cache_dir options, try replacing model_size with the local path of the model you downloaded instead of the model's name.
Ex:
```python3
model = WhisperModel("/path/faster-distil-whisper-large-v3", device="cuda")
```

**Comment by LXRee** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已收到你发送的管理学作业。

**Comment by LXRee** [comment]
Thanks to you, now it can work, but I have got another problem. It says that my CUDA driver version is insufficient for CUDA runtime version. The error is below:







but I have installed the cudnn and cublas, my navida environment is bellow, my python environment is python 3.9. So should I install the cuda 12?&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SYSTRAN/faster-whisper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SYSTRAN/faster-whisper] How to use the local cached model? (Issue #822)





 
@LXRee , hello. You don't need to pass the local_files_only and cache_dir options, try replacing model_size with the local path of the model you downloaded instead of the model's name.
 Ex:
 model = WhisperModel("/path/faster-distil-whisper-large-v3", device="cuda")

**Comment by LXRee** [comment]
This is an auto-reply email from QQ mailhello, I have recevied your email

**Comment by LXRee** [comment]
This is an auto-reply email from QQ mailhello, I have recevied your email
