### ISSUE TITLE
Will it support c++/c just like whisper.cpp?

### ISSUE THREAD

**Issue by mega-cqz** [SYSTRAN/faster-whisper#830]

**Comment by trungkienbkhn** [comment]
@mega-cqz , hello. Currently no, you can see this [comment](https://github.com/OpenNMT/CTranslate2/issues/1419#issuecomment-1682321352)

**Comment by mega-cqz** [comment]
> @mega-cqz , hello. You can see this [comment](https://github.com/OpenNMT/CTranslate2/issues/1419#issuecomment-1682321352)

Ok, i will try, thanks
