### ISSUE TITLE
Can not upload model to hub

### ISSUE THREAD

**Issue by phamkhactu** [SYSTRAN/faster-whisper#863]
I converted model whisper to faster successfully. Now I load model from local and upload to hub, but I get error:
```
AttributeError: 'WhisperModel' object has no attribute 'push_to_hub'
```
Here is my code:
```
from faster_whisper import WhisperModel


faster_model = WhisperModel("medium-faster-whisper", device="cpu")

repo_name = "QAdam/medium-faster-whisper"

faster_model.push_to_hub(repo_name)

```
I am sorry if I'm wrong and I happy for your help.

**Comment by trungkienbkhn** [comment]
@phamkhactu , FW không hỗ trợ hàm upload lên HF hub, b thử theo link này xem: https://huggingface.co/docs/transformers/model_sharing#upload-with-the-web-interface
