### ISSUE TITLE
TypeError: `pad_width` must be of integral type.

### ISSUE THREAD

**Issue by CheshireCC** [SYSTRAN/faster-whisper#865]
I get error in faster-whisper 1.0.2
TypeError: `pad_width` must be of integral type.
```
  File "d:\py_workspace\fatser_whsiper_GUI\python310\lib\site-packages\faster_whisper\transcribe.py", line 357, in transcribe
    features = self.feature_extractor(audio, chunk_length=chunk_length)
  File "d:\py_workspace\fatser_whsiper_GUI\python310\lib\site-packages\faster_whisper\feature_extractor.py", line 155, in __call__
    waveform = np.pad(waveform, [(0, self.n_samples)])
  File "d:\py_workspace\fatser_whsiper_GUI\python310\lib\site-packages\numpy\lib\arraypad.py", line 745, in pad
    raise TypeError('`pad_width` must be of integral type.')
TypeError: `pad_width` must be of integral type.
```

windows 11 
python : 3.10 
faster-whisper: 1.0.2 
numpy : 1.26
I never get this error in 1.0.1

**Comment by CheshireCC** [comment]
I fixed this bug with modified source code
feature_extractor.py line 151:
```
# self.n_samples = chunk_length * self.sampling_rate
self.n_samples = int(chunk_length * self.sampling_rate)
```

**Comment by CheshireCC** [comment]
I try to print type():
```
print(type(self.n_samples))
```
and I get result:
```
<class 'float'>
```
I dont know why this happand.
may be type of `chunk_length` parameter cause this bug.

**Comment by trungkienbkhn** [comment]
@CheshireCC , yes. This is caused by chunk_length param. chunk_length default value is 30 (standard audio processing duration for original whisper). You can change this param in the transcribe function but note that it should be [an integer value](https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/transcribe.py#L237), float value is not allowed.
Example for distil-whisper model:
```python
from faster_whisper import WhisperModel

model_size = "distil-large-v3"
model = WhisperModel(model_size, device="cuda", compute_type="float16")
segments, info = model.transcribe("audio.mp3", chunk_length=15, condition_on_previous_text=False)
```
