### ISSUE TITLE
Transcribe results being translated to different language

### ISSUE THREAD

**Issue by acn-reginald-casela** [SYSTRAN/faster-whisper#869]
Hi all,

I just want to post an issue I encountered. As the title suggests, faster-whisper transcribed the audio file in the wrong language.

This is my code for this test:
```
from faster_whisper import WhisperModel

model_size = "medium"
file = "audio.mp3"

model = WhisperModel(model_size, device="cpu", compute_type="int8")

segments, info = model.transcribe(
            file, 
            initial_prompt="Umm, hmm, Uhh, Ahh", #used to detect fillers
            temperature=0,
            vad_filter=True,
            without_timestamps=True,
            beam_size=1,
            # chunk_length=3
            )

print("Detected language '%s' with probability %f" % (info.language, info.language_probability))
print(info)
for segment in segments:
    print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
```

And the result was:

> [1.01s -> 8.40s]  Tidak ada, biar saya tolong awak dengan masalah pembayaran. Boleh saya tahu masalah apa yang awak hadapi?

I used google translate for the result and saw that the Malay sentence is close to what was said in the English audio, I'm not sure why it was translated. I checked the all_language_probs and saw that the highest prob was "ms". Given this, is there a way to prevent this? I know that setting a language helps, but the plan is to make it flexible and be able to transcribe audios of differing languages.
[audio.zip](https://github.com/user-attachments/files/15551003/audio.zip)

**Comment by acn-reginald-casela** [comment]
As an update:

I tried adding in 
`language = "en"`
to the parameters of transcribe and it was able to get the correct output. I'm just wondering why it did an auto-translate to Malay of the english speech just because of the supposed accent detected.

**Comment by trungkienbkhn** [comment]
@acn-reginald-casela , hello. I tested your audio with tiny and large-v3 model but I cannot reproduce the same behavior.
I think you should use a larger fw model to improve accuracy.

**Comment by acn-reginald-casela** [comment]
Hi @trungkienbkhn , thanks for taking a look in to this. Unfortunately, I can't change the model to large-v3 due to runtime difference. I was wondering why is the result being auto-translated to the perceived language? As I mentioned, if we were to translate the resulting Malay sentence, it's exactly what was said in the English audio I provided.

**Comment by trungkienbkhn** [comment]
I think that this problem comes from the model itself. Small models are of poorer quality and can be misidentified.

**Comment by trungkienbkhn** [comment]
Could you try to remove option `initial_prompt`, or another way, add option `condition_on_previous_text=False` ? They can also affect the quality of the transcription.

**Comment by acn-reginald-casela** [comment]
I tried your suggestion and still got the same result

> TranscriptionInfo(language='ms', language_probability=0.718927264213562, duration=8.4, duration_after_vad=7.392, all_language_probs=[('ms', 0.718927264213562), ('en', 0.236172154545784), ('hi', 0.008628533221781254), ('ta', 0.008214173838496208), ('nn', 0.0029158222023397684), ('zh', 0.002875559264793992), ('jw', 0.002814379520714283), ('ur', 0.0026052596513181925), ('ja', 0.0022859065793454647), ('tl', 0.001929903868585825), ('cy', 0.0018935619154945016), ('la', 0.0017283682245761156), ('id', 0.0013688539620488882), ('ko', 0.0011086544254794717), ('te', 0.0008453249465674162), ('es', 0.0006833726656623185), ('fr', 0.0005229057278484106), ('bn', 0.0005150276701897383), ('th', 0.0002838399959728122), ('sa', 0.0002643793122842908), ('vi', 0.0002570828073658049), ('ro', 0.00023309951939154416), ('si', 0.0002264752984046936), ('mi', 0.00022415506828110665), ('uk', 0.00019675088697113097), ('sw', 0.00018310188897885382), ('pt', 0.00018004084995482117), ('ar', 0.00017630482034292072), ('de', 0.00017257519357372075), ('fa', 0.0001712815137580037), ('ru', 0.00016164511907845736), ('bo', 0.00013485773524735123), ('sl', 0.0001224745501531288), ('km', 0.00011694607383105904), ('yo', 9.921204036800191e-05), ('it', 9.754283382790163e-05), ('tr', 8.523998985765502e-05), ('ps', 5.2971856348449364e-05), ('haw', 5.2598235924961045e-05), ('ne', 4.7894987801555544e-05), ('sn', 4.694801464211196e-05), ('af', 4.264664676156826e-05), ('da', 3.157024548272602e-05), ('bg', 2.7701573344529606e-05), ('ca', 2.5768405976123177e-05), ('my', 2.4586322979303077e-05), ('lo', 2.373584356973879e-05), ('nl', 2.1363655832828954e-05), ('gu', 2.0048217265866697e-05), ('kn', 1.469323797209654e-05), ('ml', 1.4376074432220776e-05), ('gl', 1.3536844562622719e-05), ('pl', 1.283688015973894e-05), ('no', 1.0726924301707186e-05), ('mn', 1.0559228030615486e-05), ('fi', 7.412459126499016e-06), ('cs', 7.270767127920408e-06), ('el', 7.177772204158828e-06), ('sd', 6.542033588630147e-06), ('sv', 6.469073014159221e-06), ('br', 5.58825286134379e-06), ('mr', 4.44567513113725e-06), ('hr', 4.163194716966245e-06), ('pa', 4.054710643686121e-06), ('sr', 3.9359842958219815e-06), ('oc', 3.866685801767744e-06), ('et', 3.2693187677068636e-06), ('as', 2.225538992206566e-06), ('su', 1.8509651908971136e-06), ('is', 1.6378637610614533e-06), ('sk', 1.5438191667271894e-06), ('hu', 1.4128185057415976e-06), ('lt', 1.3609195548269781e-06), ('ht', 1.3287246929394314e-06), ('he', 1.2750635960401269e-06), ('kk', 9.111548138207581e-07), ('am', 8.098955959212617e-07), ('fo', 6.531333269776951e-07), ('bs', 6.090008923820278e-07), ('lv', 5.34764410531352e-07), ('ha', 5.008893140256987e-07), ('mk', 3.3242298513869173e-07), ('eu', 2.9928241929155774e-07), ('yi', 2.8821699515901855e-07), ('be', 2.5079063448174566e-07), ('sq', 2.459919699049351e-07), ('so', 1.9651056959446578e-07), ('mt', 1.8376357502347673e-07), ('tg', 1.360576362685606e-07), ('az', 1.2905015012165677e-07), ('mg', 1.2495380019572622e-07), ('ln', 9.689276225799404e-08), ('tt', 5.781847534080953e-08), ('hy', 5.4314192254878435e-08), ('tk', 3.8713604766371645e-08), ('ba', 3.7453084189564834e-08), ('lb', 2.7359014609373844e-08), ('ka', 2.6508972794658803e-08), ('uz', 8.793286987440752e-09)], transcription_options=TranscriptionOptions(beam_size=1, best_of=5, patience=1, length_penalty=1, repetition_penalty=1, no_repeat_ngram_size=0, log_prob_threshold=-1.0, no_speech_threshold=0.6, compression_ratio_threshold=2.4, condition_on_previous_text=False, prompt_reset_on_temperature=0.5, temperatures=[0], initial_prompt=None, prefix=None, suppress_blank=True, suppress_tokens=[-1], without_timestamps=True, max_initial_timestamp=1.0, word_timestamps=False, prepend_punctuations='"\'“¿([{-', append_punctuations='"\'.。,，!！?？:：”)]}、', max_new_tokens=None, clip_timestamps='0', hallucination_silence_threshold=None), vad_options=VadOptions(threshold=0.5, min_speech_duration_ms=250, max_speech_duration_s=inf, min_silence_duration_ms=2000, window_size_samples=1024, speech_pad_ms=400))
[1.01s -> 8.40s]  Tidak ada. Biar saya tolong awak dengan masalah pembayaran. Boleh saya tahu masalah apa yang awak hadapi?

And this is my config for the transcribe task:
```
segments, info = model.transcribe(
            file, 
            temperature=0,
            vad_filter=True,
            without_timestamps=True,
            beam_size=1,
            # language="en",
            condition_on_previous_text=False
            # chunk_length=3
            )
```

**Comment by trungkienbkhn** [comment]
Could you try to remove `compute_type="int8"` ? Quantization can also give poorer quality.

**Comment by trungkienbkhn** [comment]
Another way, to improve language detection, you can try to use option [language_detection_segments](https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/transcribe.py#L309) and language_detection_threshold.

**Comment by acn-reginald-casela** [comment]
> Could you try to remove `compute_type="int8"` ? Quantization can also give poorer quality.

Did the updates on the parameters and still got the same result.

**Comment by acn-reginald-casela** [comment]
Hi @trungkienbkhn , just wanted to ask if there's a way to set like "preferred languages" or something?

**Comment by trungkienbkhn** [comment]
Unfortunately no. Currently FW only detects the language once and then applies it to the entire input audio.

**Comment by Nahid-Ahsan** [comment]
I also faced a similar problem. Any solution in here?
