### ISSUE TITLE
Local or remote?

### ISSUE THREAD

**Issue by mike99mac** [SYSTRAN/faster-whisper#870]
Hi, thought faster-whisper ran locally, but there seems to be a connection to hugginface.co on every request.  Is this to convert to text, or is it to check if the model has been downloaded?  Is there a way to remain totally local?

**Comment by trungkienbkhn** [comment]
@mike99mac , hello. You can download/save model to your local path then pass this path when initializing fw model. In this case, the model will no longer download from the hf hub.
Ex:
```python
model_path = '/path/faster-whisper-large-v3-fine-tuning'
model = WhisperModel(model_path, device="cuda")
```
