### ISSUE TITLE
Question regarding avg_logprobability

### ISSUE THREAD

**Issue by bchinnari** [SYSTRAN/faster-whisper#872]
I have lot of unsupervised speech data.
I want to fine-tune a tiny model using speech data, paired with corresponding asr hypothesis from large-v3 model.

Instead of using all the data, I would like to select those utterances with high confidence in the output.
Is avg_logprobability somehow loosely related to confidence?

**Comment by trungkienbkhn** [comment]
@bchinnari , you can refer to this [comment](https://github.com/openai/whisper/discussions/1183#discussioncomment-5585981)
