### ISSUE TITLE
Whisper invalid input feartures shape.

### ISSUE THREAD

**Issue by ivanhe123** [SYSTRAN/faster-whisper#875]
I downloaded Whisper-large-v3 from here: https://huggingface.co/Systran/faster-whisper-large-v3/tree/main
All the files exept for the .gitattributes and README.md file.
I read all the fixed and closed errors like this, and I redownloaded the files and tried every step in the closed issues, but it did not work.

Here is  the error message:
File "xxxxxsxx", line 28, in split_audio_whisper
  segments, info = model.transcribe(audio_path, beam_size=5, word_timestamps=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "xxxxxx\venv\Lib\site-packages\faster_whisper\transcribe.py", line 308, in transcribe
  encoder_output = self.encode(segment)
                   ^^^^^^^^^^^^^^^^^^^^
File "xxxxxx\venv\Lib\site-packages\faster_whisper\transcribe.py", line 610, in encode
  return self.model.encode(features, to_cpu=to_cpu)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid input features shape: expected an input with shape (1, 128, 3000), but got an input with shape (1, 80, 3000) instead

This is the files in the folder:
![image](https://github.com/SYSTRAN/faster-whisper/assets/108038846/9871c292-ed5f-46aa-a531-855e511ddcdd)

**Comment by trungkienbkhn** [comment]
@ivanhe123, have you run with the latest version 1.0.2 ? And make sure that `feature_size=128` in your preprocessor_config.json file.

**Comment by ivanhe123** [comment]
OK
It seams i am in version 0.9.0
THX
