### ISSUE TITLE
How to choose the CUDA 12 version？ Can it support CUDA 12.2？

### ISSUE THREAD

**Issue by jacobtang** [SYSTRAN/faster-whisper#879]
Latest versions of ctranslate2 support CUDA 12 only.

    model = faster_whisper.WhisperModel(
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 144, in __init__
    self.model = ctranslate2.models.Whisper(
RuntimeError: CUDA failed with error the operation cannot be performed in the present state

![image](https://github.com/SYSTRAN/faster-whisper/assets/15025269/ed50e1e0-69c8-45d2-aab8-cb4ecec06676)
I have tried many times,but still have the  RuntimeError.
Thanks!

**Comment by dancinkid6** [comment]
i am running on CUDA 12.4 and CUDNN 9.2, works perfectly, maybe u can upgrade?
btw im on RTX4090

**Comment by Akshay-AE** [comment]
> i just set it up on CUDA 12.4 and CUDNN 9.2, works perfectly, maybe u can upgrade? btw, i noticed your tesla t4 is OFF

does it still work for you? I upgraded to these versions but it doesn't work. I don't even have cudnn_ops_infer64_8.dll!!
