### ISSUE TITLE
Is faster-whisper on an old CUDNN Version?

### ISSUE THREAD

**Issue by psych0v0yager** [SYSTRAN/faster-whisper#885]
I received the following error when using faster-whisper

```
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Aborted (core dumped)
```

Other issues pointed me to install libcudnn8 via the apt-get package manager. The thing is, I have installed cudnn-9.2 as per Nvidia's official instructions. (https://developer.nvidia.com/cudnn-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local)

After viewing the cudnn.so files ```ls /usr/lib/x86_64-linux-gnu | grep libcudnn```, I noticed cudnn was correctly installed but there is no ```libcudnn_ops_infer.so.8``` or ```libcudnn_ops_infer.so.9``` file within the directory.

Is it best to delete the 9.2 install and revert back to cudnn 8, or wait for ctranslate2 to update to the latest cudnn?

**Comment by trungkienbkhn** [comment]
@psych0v0yager , hello. According to [GPU](https://github.com/SYSTRAN/faster-whisper?tab=readme-ov-file#gpu) requirements:
> Note: Version 9+ of nvidia-cudnn-cu12 appears to cause issues due its reliance on cuDNN 9 (Faster-Whisper does not currently support cuDNN 9). Ensure your version of the Python package is for cuDNN 8.

Therefor, you should back to use cudnn 8. To install `libcudnn_ops_infer.so.8`:
```
sudo apt-get install libcudnn8 libcudnn8-dev
```
