### ISSUE TITLE
language default

### ISSUE THREAD

**Issue by rbgreenway** [SYSTRAN/faster-whisper#889]
I have a situation where audio will occasionally get submitted for transcription that contains no speaking voices.  When this occurs, and no language has been specified in the transcribe call, an exception occurs in transcribe.py 

https://github.com/SYSTRAN/faster-whisper/blob/c22db5125d21d81744614f458b78604650038d3d/faster_whisper/transcribe.py#L419

I'm not sure, but I think that detected language info must come back empty and causes the max() to fail.

It would be nice to handle this situation with some sort of default language setting that gets set if it can't figure it out...or just add some sort of logic to cover for this situation.

Please forgive me if I've overlooked some way to work around this.

**Comment by ngcheeyuan** [comment]
>I have a situation where audio will occasionally get submitted for transcription that contains no speaking voices

Did you set vad_filter = True

?

**Comment by rbgreenway** [comment]
@ngcheeyuan @trungkienbkhn 
Yes, vad_filter = True in call to transcribe.  I think the problem is that there are no voices in the audio.  I am trying to transcribe phone calls, and sometimes no one answers...thus the issue.

Here's an example audio file that causes the error described in my original post:
[test_mono.zip](https://github.com/user-attachments/files/16070400/test_mono.zip)

I could just filter all my audio files with a VAD to make sure there are voices in the audio before attempting to transcribe, was just hoping I wouldn't have to do that.

**Comment by trungkienbkhn** [comment]
@rbgreenway , you can quick fix by editing this [logic](https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/transcribe.py#L364) as follows:
```python
if not self.model.is_multilingual or not audio:
    language = "en"
    language_probability = 1
```

**Comment by ngcheeyuan** [comment]
A little convoluted way would be use VAD separately and check if file is still longer than a minimum length before transcribing it.

**Comment by rbgreenway** [comment]
@ngcheeyuan @trungkienbkhn thank you both for excellent help and suggestions.
