### ISSUE TITLE
After transcription, there is still occupation of GPU memory

### ISSUE THREAD

**Issue by lesrose** [SYSTRAN/faster-whisper#891]
`from faster_whisper import WhisperModel

model = WhisperModel("/data/ai-model/faster-whisper-large-v3")
segments, info = model.transcribe("/data/resource-data/2024-06-19/gpu1/b5fa231dfc7a462d8c91dbbc36cd7c72.mp3")
for i in range(10):
time.sleep(10)`
Why is there still gpu memory usage during sleep

![image](https://github.com/SYSTRAN/faster-whisper/assets/48045297/4db1b895-551d-43e2-bd29-fd9b45d5959c)

**Comment by trungkienbkhn** [comment]
This is normal behavior. If you want to release gpu resource, you can add this logic:
```python
del model
for i in range(10):
    time.sleep(10)
```
Or another way, ctranslate2 also support `unload_model` function:
```python
model.model.unload_model()
for i in range(10):
    time.sleep(10)
```

**Comment by trungkienbkhn** [comment]
What is the error you encountered ? Could you show full code.

**Comment by lesrose** [comment]
> What is the error you encountered ? Could you show full code.
![image](https://github.com/SYSTRAN/faster-whisper/assets/48045297/c2c5e06c-06d1-4e0d-86df-a3e26bf3ad29)

![image](https://github.com/SYSTRAN/faster-whisper/assets/48045297/44bd4f45-9b7c-454a-9347-6c3798b538d1)

**Comment by trungkienbkhn** [comment]
You should to add unload_model after the generator. Because inside generator still uses the model to [decode](https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/transcribe.py#L884) segment.
