### ISSUE TITLE
Update to Silero v5

### ISSUE THREAD

**Issue by dorinclisu** [SYSTRAN/faster-whisper#894]
Silero v5 was recently released https://github.com/snakers4/silero-vad/tree/v5.0, and faster-whisper is still using v4.

**Comment by jstoone** [comment]
v1.0.1 was tagged just yesterday, which upgrades to v5
-> https://github.com/SYSTRAN/faster-whisper/releases/tag/v1.0.3

**Comment by trungkienbkhn** [comment]
You need to upgrade to faster-whisper 1.0.3
