### ISSUE TITLE
ValueError exception when no language is detected

### ISSUE THREAD

**Issue by dodysw** [SYSTRAN/faster-whisper#900]
#732 causes this exception when language is not detected.
```
    language = max(                       
ValueError: max() arg is an empty sequence
```

on

```
                    language = max(
                        detected_language_info,
                        key=lambda lang: len(detected_language_info[lang]),
                    )
```

since `detected_language_info` is an empty dict.

**Comment by dodysw** [comment]
Sample fix https://github.com/dodysw/faster-whisper/commit/126abe33ce729a7edc11af9944173fc2b7444798

**Comment by Papierkorb** [comment]
Hey @dodysw, are you planning on upstreaming your changes?

I was getting the error you've documented in `faster-whisper-server`.

For Google-ability, if someone else stumbles upon the same issue, here's how you can use dodys fork in faster-whisper-server:

1. Clone the `faster-whisper-server` repository, if not done already.
2. Modify its `requirements.txt`: Look for the line `faster-whisper==...` and replace it with this: `git+https://github.com/dodysw/faster-whisper.git@master-dody`
3. Build the container, like `docker compose build`

I'm aware that this fix is neither fully correct, nor are we here in the correct repository. Yet I figured I might as well document it and then go on from there. 😅

**Comment by dodysw** [comment]
>Hey @dodysw, are you planning on upstreaming your changes?

Thanks for the interest :D No plan yet, due to time commitment. Please copy paste it as you like. Also I'll wait until faster-whisper upstream repo a little bit slower changed.

**Comment by MahmoudAshraf97** [comment]
Should be fixed now, also more tests for empty audios will be added

**Comment by Daniel-Heo** [comment]
An error that occurs when no language for speech is obtained without setting an input language.
If you do not obtain it as follows, the error is resolved by applying the default value.
                if( not detected_language_info ):
                    language = "en"
                    language_probability = 1
                else:
                    language = max(
                        detected_language_info,
                        key=lambda lang: len(detected_language_info[lang]),
                    )
                    language_probability = max(detected_language_info[language])
