### ISSUE TITLE
Does Faster-Whisper support float8?

### ISSUE THREAD

**Issue by kalradivyanshu** [SYSTRAN/faster-whisper#913]
As far as I can tell, faster-whisper only supports int-8, f16, and f32. Does it support fp8 on GPUs like H100/L4/L40s? I might be wrong (if so let me know), but I think fp8 can give better accuracy than int8, so it will be great if we can use fp8.

Thank you for all your work, love this library!

**Comment by trungkienbkhn** [comment]
@kalradivyanshu , hello. No, we don't support fp8. For more info, see this [docs](https://opennmt.net/CTranslate2/quantization.html#quantization).
