### ISSUE TITLE
highest precision level on cpu? 

### ISSUE THREAD

**Issue by lllllliuji** [SYSTRAN/faster-whisper#926]
If I use a CPU for speech conversion, what is the highest precision that can be supported?

**Comment by ooobo** [comment]
It depends on how fast your CPU is, whether you have enough memory, and how long you are willing to wait for the transcription to finsh.

**Comment by trungkienbkhn** [comment]
@lllllliuji , hello. We now support multi quantization precision: int8, int16, fp16, bf16, vv. For more details, you can refer to this [doc](https://opennmt.net/CTranslate2/quantization.html)
