### ISSUE TITLE
For audio with a sample rate of 16kHz

### ISSUE THREAD

**Issue by joseph16388** [SYSTRAN/faster-whisper#931]
For audio with a sample rate of 16kHz, does faster-whisper translate more accurately than other sample rates? thanks！

**Comment by joseph16388** [comment]
> So, this is a more generic question for whisper models. Whisper models are trained to process audios with a sampling rate of 16000 so it works best with it.

thanks！

**Comment by silasmartin** [comment]
Does faster-whisper automatically re-sample to 16kHz like whisper does?
