### ISSUE TITLE
IMPORTANT: pyannote of the 1.0.3 source code

### ISSUE THREAD

**Issue by ckgithub2019** [SYSTRAN/faster-whisper#932]
the 1.0.3 source code I use pip to install is different from the current code on github (https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/vad.py), there are no any pyannote-related code in the 1.0.3 source code I installed, as well as the model file pyannote_vad_model.bin (https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/assets/pyannote_vad_model.bin). 
WHY?

**Comment by Jiltseb** [comment]
Because Github main is not always the latest pip release. If you want to use the latest  github version, please use `pip install git+https://github.com/SYSTRAN/faster-whisper.git`

**Comment by ckgithub2019** [comment]
> Because Github main is not always the latest pip release. If you want to use the latest github version, please use `pip install git+https://github.com/SYSTRAN/faster-whisper.git`

ok, thanks.
