### ISSUE TITLE
I can‘t find BatchedInferencePipeline.

### ISSUE THREAD

**Issue by ZHJ19970917** [SYSTRAN/faster-whisper#935]
faster_whisper == 1.0.3
from faster_whisper import WhisperModel, BatchedInferencePipeline

model = WhisperModel("medium", device="cuda", compute_type="float16")
batched_model = BatchedInferencePipeline(model=model)
segments, info = batched_model.transcribe("audio.wav", batch_size=16)

for segment in segments:
    print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))

ImportError: cannot import name 'BatchedInferencePipeline' from 'faster_whisper'

**Comment by zh-plus** [comment]
The batched inference pull request has been merged but hasn't been published to PYPI yet. Try installing faster-whisper directly from the source:
```shell
pip install --force-reinstall "faster-whisper @ https://github.com/SYSTRAN/faster-whisper/archive/refs/heads/master.tar.gz"
```

**Comment by piyushmaharana** [comment]
`websockets==12.0
speechbrain==1.0.0
pyannote.audio==3.2.0
asyncio==3.4.3
sentence-transformers==2.7.0
transformers==4.40.2
torchvision~=0.18.0
torch~=2.3.0
faster-whisper @ https://github.com/SYSTRAN/faster-whisper/archive/refs/heads/master.tar.gz`

example requirements.txt file

**Comment by greg2705** [comment]
Hello, Im wroking behind a proxy having only access to pypi,any ideas when the package willl be upload on pypi ? Thanks !

**Comment by tea-dot-ill-stew** [comment]
> Hello, Im wroking behind a proxy having only access to pypi,any ideas when the package update willl be upload on pypi ? Thanks !

Any update on this, for us pypi restricted users?

**Comment by Salomonmejia1** [comment]
I downloaded it in a pc with free internet and transfer to the server with STT. that can help

**Comment by MahmoudAshraf97** [comment]
Version `1.1.0` just released to PyPI
