### ISSUE TITLE
RuntimeError: Unsupported model binary version. This executable supports models with binary version v6 or below, but the model has binary version v1936876918.

### ISSUE THREAD

**Issue by DearTan** [SYSTRAN/faster-whisper#959]
When I execute with faster-whisper-large-v2 model in my python project, like these codes:
  `path = r"/Users/admin/Documents/models/faster-whisper-large-v2" 
   model = WhisperModel(model_size_or_path=path, device="cpu", compute_type="int8", local_files_only=True)` the above error occurred. 
 how to solve this problem? I have tried many times to download the model (git clone https://huggingface.co/guillaumekln/faster-whisper-large-v2) , but it still doesn't work. 
 Thanks!

**Comment by YMCVICTOR** [comment]
I also have this problem, how did you solve it?
