### ISSUE TITLE
Are there any plans to publish the latest code to pypi？

### ISSUE THREAD

**Issue by wildwind0** [SYSTRAN/faster-whisper#976]
The new features, such as "multi-segment language detection"  and "Batched faster-whisper", are not available on the latest version 1.0.3. Do you have any plans to release it?Is there anything I should be aware of if I want to upgrade to use the new features?

**Comment by MahmoudAshraf97** [comment]
it's still not mature yet, there are some fixes pending and once it's stable it'll be merged

**Comment by MahmoudAshraf97** [comment]
Version `1.1.0` just released to PyPI
