### ISSUE TITLE
Very bigger segment (chunk) size (almost 30 second each) with BatchedInferencePipeline

### ISSUE THREAD

**Issue by alamnasim** [SYSTRAN/faster-whisper#985]
I am using BatchedInferencePipeline on a audio file of 1 hr duration and getting each segment of almost 30 sec each.
When I don't use BatchedInferencePipeline, segment duration is 1-2 sec and it's been seperated on VAD.

I hope BatchedInferencePipeline is also using VAD to make chunk.

Please suggest to get 5-6 sec chunks (segments) using BatchedInferencePipeline.

Thanks

**Comment by MahmoudAshraf97** [comment]
use `without_timestamps=False` when transcriping, note that this might reduce transcription quality on both batched and non batched

**Comment by alamnasim** [comment]
Thanks for the quick reply.

Transcription latency has increased by 3X, earlier it was 50 sec for 1.5 hr of audio duration, now its 160 sec.

**Comment by MahmoudAshraf97** [comment]
This is a problem with CT2, not related to faster whisper, the latency increases with larger batch sizes so try lowering it until you're satisfied

**Comment by toanhn** [comment]
> use `without_timestamps=False` when transcriping, note that this might reduce transcription quality on both batched and non batched

You save my life, thanks Bro
